default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: UnderControl
  password: admin123
  host: localhost
  port: 5433
  
development:
  <<: *default
  database: djsonorizacao_dev
  schema_search_path: myapp,sharedapp,public
  

test:
  <<: *default
  database: djsonorizacao_test
  #schema_search_path: myapp,sharedapp,public
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

production:
  <<: *default
#  database: djsonorizacao_production
#  schema_search_path: myapp,sharedapp,public
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>