default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: myapp,sharedapp,public
  username: UnderControl
  password: admin123
  host: localhost
  port: 5433
  #port: 5432
  
development:
  <<: *default
  database: djsonorizacao_dev
  

test:
  <<: *default
  database: djsonorizacao_test
  
production:
  <<: *default
  database: djsonorizacao_production
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>