# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#########################################
########### TIPOS DE EVENTOS ############
#########################################
CORPORATIVO = TipoEvento.create( descricao: "CORPORATIVO")
FORMATURA = TipoEvento.create( descricao: "FORMATURA")
CASAMENTO = TipoEvento.create( descricao: "CASAMENTO")
DEBUTANTE = TipoEvento.create( descricao: "DEBUTANTE")
ANIVERSARIO = TipoEvento.create( descricao: "ANIVERSARIO")
BODAS = TipoEvento.create( descricao: "BODAS")
LOCACAO = TipoEvento.create( descricao: "LOCAÇÃO")
OUTROS = TipoEvento.create( descricao: "OUTROS")


#########################################
############### CLIENTES ################
#########################################
ALDOSILVESTRE = Cliente.create(nome: "ALDO SILVESTRE", telefone: "-", email: "-", como_conheceu: "ALDO SILVESTRE")
ALESSANDRAEMARCIO = Cliente.create(nome: "ALESSANDRA E MARCIO", telefone: "999391981", email: "legomes456@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
ALEXANDREFORA = Cliente.create(nome: "ALEXANDRE FORA", telefone: "-", email: "", como_conheceu: "Não informado")
ALINE = Cliente.create(nome: "ALINE", telefone: "19 98851-8722", email: "cerimonialalinebeatriz@gmail.com", como_conheceu: "cerimonial aline beatriz")
AMANDADEPAOLA = Cliente.create(nome: "AMANDA DE PAOLA", telefone: "992997826", email: "amandadepaola@hotmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
ANACAROLINA = Cliente.create(nome: "ANA CAROLINA", telefone: "15 99148-2728", email: "carolcacace@hotmail.com ", como_conheceu: "INDICAÇÃO DE CLIENTE")
ANACAROLINAELUIZ = Cliente.create(nome: "ANA CAROLINA E LUIZ", telefone: "993088040", email: "anacarolina_mgomes@outlook.com", como_conheceu: "MALU PAN")
ANACLAUDIA = Cliente.create(nome: "ANA CLAUDIA", telefone: "981637165", email: "cryedinha@hotmail.com", como_conheceu: "FACEBOOK")
ANAFLAVIAEJEFERSON = Cliente.create(nome: "ANA FLAVIA E JEFERSON", telefone: "13996627557", email: "anaflaviavet92@outlook.com", como_conheceu: "FEIRA BUFFET CANOA")
ANAPAULACASALMARINAEPEDRO = Cliente.create(nome: "ANA PAULA - CASAL MARINA E PEDRO", telefone: "992871064", email: "apl.aranha@gmail.com", como_conheceu: "Não informado")
ANDRESSA = Cliente.create(nome: "ANDRESSA", telefone: "988221220", email: "15anosnanda@gmail.com", como_conheceu: "INDICAÇAO DE UM PROFISSIONAL")
ANE = Cliente.create(nome: "ANE", telefone: "11 99606-7977", email: "anecarol.p@gmail.com", como_conheceu: "Não informado")
ANNEELUCAS = Cliente.create(nome: "ANNE E LUCAS", telefone: "11981880355", email: "anne.layze@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
ARIANEEVALENTIN = Cliente.create(nome: "ARIANE E VALENTIN", telefone: "994848439", email: "ary-fisio@hotmail.com", como_conheceu: "ANGELINOS")
ARTHUR = Cliente.create(nome: "ARTHUR", telefone: "991796364", email: "penteado.arthur@gmail.com", como_conheceu: "Não informado")
BARBARAELUCAS = Cliente.create(nome: "BARBARA E LUCAS", telefone: "996855684", email: "barbara_tebalde@hotmail.com", como_conheceu: "FEIRA CIRQUITO DAS AGUAS")
BARBARASOUZA = Cliente.create(nome: "BARBARA SOUZA", telefone: "11 96242-1210 ", email: "barbara.souza@semparar.net, barbaraejeison@gmail.com", como_conheceu: "Não informado")
BIANCACLARA = Cliente.create(nome: "BIANCA CLARA ", telefone: "99696-3568                        ", email: "", como_conheceu: "DINA LELLIT")
BRUNAEPEDRO = Cliente.create(nome: "BRUNA E PEDRO", telefone: "997636394", email: "bruna_ravara@hotmail.com", como_conheceu: "FACEBOOK")
BRUNAMARCELAEDIEGO = Cliente.create(nome: "BRUNA - (MARCELA E DIEGO)", telefone: "33874316", email: "eventos@parperfeitocerimonial.com.br", como_conheceu: "PAR PERFEITO")
BRUNAOLIVEIRA = Cliente.create(nome: "BRUNA OLIVEIRA", telefone: "91522199", email: "brunaeaoliveira@gmail.com", como_conheceu: "INDICAÇAO DE UM PROFISSIONAL")
BrunaSumiregi = Cliente.create(nome: "Bruna Sumiregi", telefone: "-", email: "-", como_conheceu: "CASAMENTOS.COM.BR")
CAMILA = Cliente.create(nome: "CAMILA", telefone: "11 98735-0069", email: "cc.arna@ig.com.br", como_conheceu: "CASAMENTOS.COM.BR")
CAMILAEBRUNO = Cliente.create(nome: "CAMILA E BRUNO", telefone: "NÃO DEIXOU", email: "camilaebruno050518@gmail.com", como_conheceu: "Não informado")
CAMILAEFABIO = Cliente.create(nome: "CAMILA E FABIO  ", telefone: "-", email: "camilaefabio1205@gmail.com", como_conheceu: "RENATA 2M EVENTOS")
CAMILAPICCELICHOQUETA = Cliente.create(nome: "CAMILA PICCELI CHOQUETA", telefone: "998702985", email: "", como_conheceu: "DINA LELLIT")
CARINAEANTONY = Cliente.create(nome: "CARINA E ANTONY", telefone: "992184321 OU 991516363", email: "cssolon@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
CARLAANALUISA = Cliente.create(nome: "CARLA - ANA LUISA", telefone: "19 99339-0523", email: "andrechukma@yahoo.com.br", como_conheceu: "ANGELINOS")
CAROLINACREPALDIETHALLES = Cliente.create(nome: "CAROLINA CREPALDI E THALLES", telefone: "3329-0422", email: "ca_ermani@hotmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
CAROLINAPASSARELLI = Cliente.create(nome: "CAROLINA PASSARELLI", telefone: "11981051584", email: "carolinapassarelli@uol.com.br", como_conheceu: "INTERNET")
CAROLINEBRITO = Cliente.create(nome: "CAROLINE BRITO", telefone: "32966259", email: "carol.brito@hotmail.com", como_conheceu: "INTERNET")
CAROLINEEJOAO = Cliente.create(nome: "CAROLINE E JOAO", telefone: "991760198", email: "caa.felix@hotmail.com", como_conheceu: "QUEMCASAQUERSITE")
CASSIATAYRINE = Cliente.create(nome: "CASSIA TAYRINE", telefone: "994787808", email: "tayrinecassia@gmail.com", como_conheceu: "INTERNET")
CLAUDIATHIAGOHADI = Cliente.create(nome: "CLAUDIA THIAGO HADI", telefone: "WHATS", email: "thiago@thiagohadi.com.br", como_conheceu: "THIAGO HADI")
CLELIAMDOPRADO = Cliente.create(nome: "CLÉLIA M DO PRADO ", telefone: "19-974152464", email: "mayaraprado62@gmail.com", como_conheceu: "REDE SOCIAL")
CYBELLE = Cliente.create(nome: "CYBELLE", telefone: "991081273", email: "manzzi_feijo@yahoo.com.br", como_conheceu: "INDICAÇÃO DE UM PROFISSONAL")
DAIANEARAUJO = Cliente.create(nome: "DAIANE ARAUJO", telefone: "41 77 913 41 63", email: "araujo.paolieri@gmail.com", como_conheceu: "ANDRE AIMEC")
DANIELA1 = Cliente.create(nome: "DANIELA", telefone: "19 99152-3937", email: "WTZP", como_conheceu: "Não informado")
DANIELA2 = Cliente.create(nome: "DANIELA", telefone: "993474745", email: "dani.mq21@hotmail.com", como_conheceu: "INTERNET")
DANIELLIARAUJOCOSTA = Cliente.create(nome: "DANIELLI ARAUJO COSTA", telefone: "98898-2814", email: "danielli.araujocosta@hotmail.com", como_conheceu: "Não informado")
DANIELLIRAMOSTONHAI = Cliente.create(nome: "DANIELLI RAMOS TONHAI", telefone: "981638599", email: "danielletonhai@gmail.com", como_conheceu: "GOOGLE")
DEBORA = Cliente.create(nome: "DEBORA", telefone: "11996971757", email: "debora.passerine@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
DERIO = Cliente.create(nome: "DERIO", telefone: "989442361", email: "WTZP", como_conheceu: "NUCLEAR")
DJKUKAVICENTIN = Cliente.create(nome: "DJ KUKA VICENTIN", telefone: "11976688722", email: "kucavicentini@hotmail.com", como_conheceu: "VIA ANDRE CURADO")
ELAINE = Cliente.create(nome: "ELAINE    ", telefone: "98841-4865", email: "", como_conheceu: "DINA LELLIT")
ELIZABETHNEGRAES = Cliente.create(nome: "ELIZABETH NEGRAES", telefone: "1137985432", email: "elizabeth.negraes@hotmail.com", como_conheceu: "INTERNET")
ELLEN = Cliente.create(nome: "ELLEN", telefone: "11 95372-0659", email: "ellendalete@hotmail.com", como_conheceu: "INSTAGRAM")
ERICDEMOURABRAMBILA = Cliente.create(nome: "ERIC DE MOURA BRAMBILA", telefone: "996341820", email: "contatoericmoura@gmail.com", como_conheceu: "INTERNET")
ERIKAKAMPOS = Cliente.create(nome: "ERIKA KAMPOS", telefone: "99214-5406", email: "erika.campos92@yahoo.com.br", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
FABRINARIBEIRO = Cliente.create(nome: "FABRINA RIBEIRO", telefone: "989685953", email: "fabrina.ribeiro22@gmail.com", como_conheceu: "ANUNCIO NA INTERNET")
FELIPEMOREIRA = Cliente.create(nome: "FELIPE MOREIRA", telefone: "987712506", email: "feliper.moreira@hotmail.com", como_conheceu: "INTERNET")
FERNANDA1 = Cliente.create(nome: "FERNANDA", telefone: "993825119", email: "fernandassoave@gmail.com", como_conheceu: "INTERNET")
FERNANDA2 = Cliente.create(nome: "FERNANDA", telefone: "992424692", email: "fer-ps@hotmail.com", como_conheceu: "REDE SOCIAL")
FERNANDOASSISePATRICIA = Cliente.create(nome: "FERNANDO ASSIS e PATRICIA", telefone: "997190847", email: "nando_assis87@yahoo.com.br", como_conheceu: "GOOGLE")
FERNANDOECAROL = Cliente.create(nome: "FERNANDO E CAROL", telefone: "98293-9262", email: "fernando.s.f.garcia@hotmail.com", como_conheceu: "VIA ANDRE CURADO")
FLAVIACANTUSIOALINEELUCAS = Cliente.create(nome: "FLAVIA CANTUSIO - ALINE E LUCAS", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIOBEATRIZEFABRICIO = Cliente.create(nome: "FLAVIA CANTUSIO - BEATRIZ E FABRICIO", telefone: "32520975 - 11 982183524", email: "flavia@flaviacantusio.com.br, biafgomes@hotmail.com", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIOERIKAEMAURICIO = Cliente.create(nome: "FLAVIA CANTUSIO - ERIKA E MAURICIO", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIOGIOVANAEGUILHERME = Cliente.create(nome: "FLAVIA CANTUSIO - GIOVANA E GUILHERME", telefone: "99647-2147 ou 3252-0975 ", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIORAFAELAELUCAS = Cliente.create(nome: "FLAVIA CANTUSIO - RAFAELA E LUCAS", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "Não informado")
FLAVIACANTUSIOSTEPHANIEEEDUARDO = Cliente.create(nome: "FLAVIA CANTUSIO - STEPHANIE E EDUARDO", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIADIAS = Cliente.create(nome: "FLAVIA DIAS", telefone: "NÃO DEIXOU", email: "flavia.hdias@hotmail.com", como_conheceu: "ANGELINOS")
FLAVIAERICAEMAURICIO = Cliente.create(nome: "FLAVIA - ERICA E MAURICIO", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "Não informado")
FLAVIOCRUZ = Cliente.create(nome: "FLAVIO CRUZ", telefone: "11950790104", email: "flaviomfcruz@gmail.com", como_conheceu: "INTERNET")
GABRIELA = Cliente.create(nome: "GABRIELA", telefone: "992269996", email: "casamentobruwgabi@gmail.com", como_conheceu: "SITE DJ SONORIZACAO")
GABRIELAERODRIGO = Cliente.create(nome: "GABRIELA E RODRIGO", telefone: "99917-4400", email: "gabrielareginato87@gmail.com, rsruschel@gmail.com", como_conheceu: "RITA PONTES")
GABRIELASANTANA = Cliente.create(nome: "GABRIELA SANTANA", telefone: "992269996", email: "gabriella.satt@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
GLAUCIAERENAN = Cliente.create(nome: "GLAUCIA E RENAN", telefone: "98262-1391", email: "glau.lira16@hotmail.com, renann_sousa@hotmail.com", como_conheceu: "Não informado")
HEBERFOTOSGABRIEL = Cliente.create(nome: "HEBER FOTOS (GABRIEL)", telefone: "38621004 ou 999141393", email: "hebereventos@gmail.com", como_conheceu: "Não informado")
HELENAGUERRA = Cliente.create(nome: "HELENA GUERRA ", telefone: "99663-6315                        ", email: "", como_conheceu: "DINA LELLIT")
ISABELACAUMEPAULO = Cliente.create(nome: "ISABELA CAUM E PAULO", telefone: "99832-4590", email: "isabelacristinacaum@hotmail.com", como_conheceu: "INTERNET")
JACKFOCUSPRODUCOES = Cliente.create(nome: "JACK - FOCUS PRODUÇÕES", telefone: "-", email: "comercial@focusproducoes.com.br", como_conheceu: "Não informado")
JAQUELINE = Cliente.create(nome: "JAQUELINE", telefone: "-", email: "-", como_conheceu: "CASAMENTOS.COM.BR")
JAQUELINERAPHAELZOTARELI = Cliente.create(nome: "JAQUELINE (RAPHAEL ZOTARELI)", telefone: "99931-7179", email: "rafael.zotarelli@gmail.com", como_conheceu: "BUFFET SANTA MARIA")
JESSICA1 = Cliente.create(nome: "JESSICA", telefone: "988181132", email: "jessica.marquesani@gmail.com", como_conheceu: "GOOGLE")
JESSICA2 = Cliente.create(nome: "JESSICA", telefone: "99279-5930", email: "casamento2018.jehlucca@gmail.com", como_conheceu: "CASAMENTOS.COM.BR")
JESSICAGEREMIAS = Cliente.create(nome: "JESSICA  GEREMIAS                        ", telefone: "971529265", email: "", como_conheceu: "DINA LELLIT")
JOYCESANTOPEDRO = Cliente.create(nome: "JOYCE SANTO PEDRO", telefone: "999464844", email: "joyce-s-pedro@hotmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
JULIA = Cliente.create(nome: "JULIA", telefone: "11 99751-6333", email: "WHATS", como_conheceu: "MEDISONS")
JULIADEOLIVEIRA = Cliente.create(nome: "JULIA DE OLIVEIRA", telefone: "11975789487", email: "oliveira.oliveira51@hotmail.com.br", como_conheceu: "INTERNET")
JULIAISABELCURY = Cliente.create(nome: "JULIA - ISABEL CURY", telefone: "36336127", email: "julia.isabelcury@gmail.com", como_conheceu: "ISABEL CURY")
JULIANACAMPOS = Cliente.create(nome: "JULIANA CAMPOS", telefone: "991919431", email: "gcampos.juliana@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
JULIANACESARGRANJA = Cliente.create(nome: "JULIANA CESAR GRANJA", telefone: "11 991484367", email: "jucesargranja@gmail.com", como_conheceu: "INSTAGRAN")
JULIANAEEVERSON = Cliente.create(nome: "JULIANA E EVERSON", telefone: "JULIANA - 99721-2877           EVERSON - 99692-4988", email: "palaro.juliana@gmail.com", como_conheceu: "MOSTRA TH HADI")
JULIANAGURIAN = Cliente.create(nome: "JULIANA GURIAN", telefone: "99120-6849", email: "jugurian@hotmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
JULIOOHIRA = Cliente.create(nome: "JULIO OHIRA", telefone: "991143535", email: "julioc.ohira@outlook.com.br", como_conheceu: "INTERNET")
KARENEDANILO = Cliente.create(nome: "KAREN E DANILO", telefone: "991496673", email: "karenpg6@hotmail.com", como_conheceu: "FACEBOOK")
KARINAFUNARI = Cliente.create(nome: "KARINA FUNARI", telefone: "3881-9286", email: "karinaafunari@eaton.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
KARINENICOLETI = Cliente.create(nome: "KARINE NICOLETI", telefone: "97377-7863", email: "karine_nicolety@hotmail.com", como_conheceu: "Não informado")
KELMA = Cliente.create(nome: "KELMA", telefone: "32728683", email: "kelmabalista@hotmail.com", como_conheceu: "INTERNET")
KENNIASILVA = Cliente.create(nome: "KENNIA SILVA", telefone: "19998427584", email: "fskennia@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
LAIS = Cliente.create(nome: "LAIS", telefone: "991966977", email: "gabi.lais@hotmail.com", como_conheceu: "INTERNET")
LARISSAEVINICIUS = Cliente.create(nome: "LARISSA E VINICIUS  ", telefone: "-", email: "pavani_91@hotmail.com", como_conheceu: "RENATA 2M EVENTOS")
LARISSAHADASSAELUCIANO = Cliente.create(nome: "LARISSA - HADASSA E LUCIANO", telefone: "991823236", email: "contato@larissafarhat.comb.r", como_conheceu: "Não informado")
LEILAHPASSOS = Cliente.create(nome: "LEILAH PASSOS", telefone: "11 4237 2415", email: "leilah_passos@hotmail.com, julianalacerda@lufteventos.com.br, luftassessoria@gmail.com", como_conheceu: "INTERNET")
LETICIACRISTINACARAZATTOETHIAGOSOARESSILVA = Cliente.create(nome: "LETICIA CRISTINA CARAZATTO E THIAGO SOARES SILVA", telefone: "981405069", email: "leticiacarazzatto@hotmail.com, soaresthia@gmail.com", como_conheceu: "INTERNET")
LETICIAEJOAOPAULO = Cliente.create(nome: "LETICIA E JOAO PAULO", telefone: "LETICIA - 99353-7779                        JOAO PAULO - 99283-4904", email: "leticia.silva@hotmail.com", como_conheceu: "MOSTRA TH HADI")
LIA = Cliente.create(nome: "LIA", telefone: "33657280", email: "lia.wil@terra.com.br", como_conheceu: "GOOGLE")
LIDIANEBASCHIERA = Cliente.create(nome: "LIDIANE BASCHIERA", telefone: "98365-7575", email: "lidiane.arquitetura@hotmail.com", como_conheceu: "DINA LELLIT")
LIVIACASTRO = Cliente.create(nome: "LÍVIA CASTRO                        ", telefone: "991996558", email: "", como_conheceu: "DINA LELLIT")
LIVIADESOUZARODRIGUES = Cliente.create(nome: "LÍVIA DE SOUZA RODRIGUES             ", telefone: "982731384", email: "", como_conheceu: "DINA LELLIT")
LUCASEJULIANA = Cliente.create(nome: "LUCAS E JULIANA", telefone: "99155-5305", email: "luc.mendes13@gmail.com", como_conheceu: "MONTAGEM NO LOCAL")
LUCIANAROCHASOARES = Cliente.create(nome: "LUCIANA ROCHA SOARES", telefone: "998133298", email: "lulu.lrs@gmail.com", como_conheceu: "INTERNET")
LUCIMARPOSSARI = Cliente.create(nome: "LUCIMAR POSSARI", telefone: "98167-9480", email: "lucimar@lucimarpossari.com.br", como_conheceu: "LUCIMAR POSSARI")
MAISAMOREIRA = Cliente.create(nome: "MAÍSA MOREIRA", telefone: "98440-8764", email: "", como_conheceu: "DINA LELLIT")
MARCELA = Cliente.create(nome: "MARCELA", telefone: "19 99953-2227", email: "marcela.degrossoli@outlook.com ", como_conheceu: "Não informado")
MARCELOAMARAL = Cliente.create(nome: "MARCELO AMARAL", telefone: "1195177-7542 OU 11 5694-4122", email: "marcelo.amaral1@bayer.com", como_conheceu: "Não informado")
MARGARETHBARROS = Cliente.create(nome: "MARGARETH BARROS", telefone: "99615-2228", email: "margarethbarros@terra.com.br, contato@margarethbarros.com.br", como_conheceu: "MARGARETH BARROS")
MARIANA = Cliente.create(nome: "MARIANA", telefone: "991131067", email: "marianamoreiravet@hotmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
MARIANAJACOBERENATO = Cliente.create(nome: "MARIANA JACOB  E RENATO", telefone: "998128188", email: "mariana.romanello@gmail.com, rseiti@gmail.com", como_conheceu: "RACHEL MIELLE")
MARIAVITORIA = Cliente.create(nome: "MARIA VITORIA", telefone: "997879373", email: "mavi.leao@gmail.com", como_conheceu: "INTERNET")
MARINAEANDRE = Cliente.create(nome: "MARINA E ANDRE", telefone: "11 98221 2336, 11 97336 0905", email: "marinaeandre2018@gmail.com", como_conheceu: "Não informado")
MAYRABONIN = Cliente.create(nome: "MAYRA BONIN", telefone: "99783-1718", email: "WHATS", como_conheceu: "LAURA SAVITCI")
MILENACAMPOS = Cliente.create(nome: "MILENA CAMPOS", telefone: "993324111", email: "", como_conheceu: "DINA LELLIT")
NADIAEGUSTAVO = Cliente.create(nome: "NADIA E GUSTAVO", telefone: "974074917", email: "nadiaferreira.almeida@gmail.com, gustavo8alvarenga@gmail.com", como_conheceu: "PAR PERFEITO")
NATALIA = Cliente.create(nome: "NATALIA", telefone: "98720-0072", email: "Natalia-sbm@outlook.com", como_conheceu: "INTERNET")
NATALIAEGUILHERME = Cliente.create(nome: "NATALIA E GUILHERME", telefone: "98128-1365 OU 992738004", email: "nanascferraz@gmail.com", como_conheceu: "THIAGO HADI")
NATALIAPOLONICORREA = Cliente.create(nome: "NATALIA POLÔNI CORRÊA", telefone: "984009546", email: "", como_conheceu: "DINA LELLIT")
NATALIEBRUNO = Cliente.create(nome: "NÁTALI E BRUNO", telefone: "11 97101 1992", email: "natali.romano@gmail.com", como_conheceu: "Não informado")
NATHALIASUNIGAEFERNANDO = Cliente.create(nome: "NATHALIA SUNIGA E FERNANDO", telefone: "999224343", email: "nathaliasuniga@cvc.com.br, nathi.fer.2018@gmail.com", como_conheceu: "SITE DECORAÇÃO")
NAYARAMACANOSSO = Cliente.create(nome: "NAYARA MACANOSSO                         ", telefone: "988670107", email: "", como_conheceu: "DINA LELLIT")
NEMELLYERAFAEL = Cliente.create(nome: "NEMELLY E RAFAEL", telefone: "994925000", email: "WHATS", como_conheceu: "GOOGLE")
NICOLEKARINAAMAE = Cliente.create(nome: "NICOLE (KARINA A MAE)", telefone: "988373030 OU 987313030 ", email: "WHATS", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
PALOMAERODRIGOCARLAROSSINI = Cliente.create(nome: "PALOMA E RODRIGO (CARLA ROSSINI)", telefone: "11 99215-5341", email: "carla@carlarossini.com.br", como_conheceu: "CARLA ROSSINI EDILAYNE FERRAZ")
PATRICIA = Cliente.create(nome: "PATRICIA", telefone: "982257112", email: "patriciaevesoares@gmail.com", como_conheceu: "INSTAGRAM")
PATRICIATENORIO = Cliente.create(nome: "PATRICIA TENORIO", telefone: "997945658", email: "drapatriciatenorio@bol.com.br", como_conheceu: "DINA LELLIT")
PAULA = Cliente.create(nome: "PAULA", telefone: "98127-2229", email: "  ", como_conheceu: "Não informado")
PAULOHENRIQUEDASILVA = Cliente.create(nome: "PAULO HENRIQUE DA SILVA", telefone: "998281804", email: "paulo_henriquesolva@yahoo.com.br", como_conheceu: "YOUTUBE")
PAULORBERNARDES = Cliente.create(nome: "PAULO R BERNARDES", telefone: "9 9626-3341", email: "bernardes.paulor@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
PRISCILA = Cliente.create(nome: "PRISCILA", telefone: "19 99112-7878", email: "priscilataveira@yahoo.com.br", como_conheceu: "KRATOS")
PRISCILAEJOAO = Cliente.create(nome: "PRISCILA E JOÃO", telefone: "99448-7357", email: "pri.dalmolin.carvalho@gmail.com", como_conheceu: "CRIS BLESS")
RAPHAELALVEZ = Cliente.create(nome: "RAPHAEL ALVEZ", telefone: "98321-7473", email: "rafaelalvescerimonial@gmail.com", como_conheceu: "RAFAEL ALVES")
RAQUELEGUILHERME = Cliente.create(nome: "RAQUEL E GUILHERME", telefone: "995920592", email: "raquel@smass.com.br", como_conheceu: "Não informado")
REBECAEFELIPE = Cliente.create(nome: "REBECA E FELIPE  ", telefone: "-", email: "rebeca.s.venturini@gmail.com", como_conheceu: "RENATA 2M EVENTOS")
RENATA2MEVENTOSHELOISAEFELIPE = Cliente.create(nome: "RENATA 2M EVENTOS - HELOISA E FELIPE", telefone: "996825662", email: "helo_poltronieri@hotmail.com, renata@doismeventos.com.br", como_conheceu: "2M EVENTOS")
RENATASARITAEEDUARDO = Cliente.create(nome: "RENATA - SARITA E EDUARDO ", telefone: "99682-5662", email: "saritaeeduardo@gmail.com, renata@doismeventos.com.br", como_conheceu: "RENATA 2M EVENTOS")
RICARDODOPRADOLAIA = Cliente.create(nome: "RICARDO DO PRADO LAIA", telefone: "998348461", email: "prado.r10@gmail.com", como_conheceu: "INTERNET")
RICARDOEJULIANA = Cliente.create(nome: "RICARDO E JULIANA", telefone: "99786-9787", email: "frealdoricardo@hotmail.com", como_conheceu: "DEGUSTAÇÃO ANGELINOS")
RITAEGERALDO = Cliente.create(nome: "RITA E GERALDO", telefone: "988600624", email: "barbarasousalopes@hotmail.com", como_conheceu: "Não informado")
ROBERTAEKAIO = Cliente.create(nome: "ROBERTA E KAIO  ", telefone: "-", email: "ro.raphaelli@gmail.com", como_conheceu: "RENATA 2M EVENTOS")
ROBERTFELDER = Cliente.create(nome: "ROBERT FELDER", telefone: "11 983678490", email: "felder_robert@hotmail.com", como_conheceu: "Não informado")
ROSANALEITE = Cliente.create(nome: "ROSANA LEITE", telefone: "982445440", email: "rosana.leita@hotmail.com", como_conheceu: "INSTAGRAM")
SALETEMICHELEEFLAVIO = Cliente.create(nome: "SALETE - MICHELE E FLAVIO", telefone: "974043043", email: "contato@saletecoelho.com.br", como_conheceu: "INTERNET")
SILVIA = Cliente.create(nome: "SILVIA", telefone: "11975958555", email: "silvia@airtraining.com.br", como_conheceu: "REVISTA")
SONIA = Cliente.create(nome: "SONIA", telefone: "991115808", email: "sonialevantezi@gmail.com", como_conheceu: "SUIT FILMES")
SULAMITAFERREIRAPICCOLIeMATHEUS = Cliente.create(nome: "SULAMITA FERREIRA PICCOLI e MATHEUS", telefone: "998514222 ou 98298-9957", email: "sulamitafp@hotmail.com", como_conheceu: "CASAMENTOS.COM.BR")
TALITAECLEVERTON = Cliente.create(nome: "TALITA E CLEVERTON", telefone: "99221-1183", email: "", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
TANIAMARIAFORTUNATO = Cliente.create(nome: "TÂNIA MARIA FORTUNATO", telefone: "981572646", email: "", como_conheceu: "DINA LELLIT")
TATIANA = Cliente.create(nome: "TATIANA", telefone: "19 99633-1355", email: "tatiflauzino@gmail.com", como_conheceu: "Não informado")
TAYNA = Cliente.create(nome: "TAYNÁ", telefone: "992255388", email: "tayna.santtos1@outlook.com", como_conheceu: "INTERNET")
THAINAEHEINRIQUE = Cliente.create(nome: "THAINA E HEINRIQUE", telefone: "99752-6051", email: "thaaipinheiro@hotmail.com", como_conheceu: "2M EVENTOS")
THAINAEHENRIQUE = Cliente.create(nome: "THAINA E HENRIQUE ", telefone: "-", email: "thaaipinheiro@hotmail.com", como_conheceu: "RENATA 2M EVENTOS")
THAISCAROLINEERENAN = Cliente.create(nome: "THAIS CAROLINE  E RENAN", telefone: "993912292", email: "taiserenan@yahoo.com, taiserenan@yahoo.com.br, tcfeichas@hotmail.com", como_conheceu: "DINA LELLIT")
THAISEPEDRO = Cliente.create(nome: "THAIS E PEDRO  ", telefone: "-", email: "td.pina@bol.com.br", como_conheceu: "RENATA 2M EVENTOS")
THAISPAOLA = Cliente.create(nome: "THAIS PAOLA", telefone: "993762128, 99376212", email: "thais.corsatto@hotmail.com", como_conheceu: "ANUNCIO NA INTERNET")
THATIANEFANTINI = Cliente.create(nome: "THATIANE FANTINI", telefone: "983583059", email: "contato@fantini.adv.br", como_conheceu: "ANUNCIO NA INTERNET")
THAYNARA = Cliente.create(nome: "THAYNARA ", telefone: "99894-4609", email: "", como_conheceu: "DINA LELLIT")
THIAGOARTMIDIA = Cliente.create(nome: "THIAGO ART MIDIA", telefone: "WTZP", email: "-", como_conheceu: "Não informado")
TULIO = Cliente.create(nome: "TULIO", telefone: "97155-0123", email: "tulio_manzano@hotmail.com", como_conheceu: "INDICAÇÇÃO DE UM PROFISSIONAL")
VALDICEABREU = Cliente.create(nome: "VALDICE ABREU", telefone: "11 99243-3926", email: "val.amelia@valamelia.com.br", como_conheceu: "VALDICE ABREU")
VANESSAFACCHIN = Cliente.create(nome: "VANESSA FACCHIN", telefone: "993589970", email: "vanessa.facchin@hotmail.com", como_conheceu: "INTERNET")
VANESSARODRIGUES = Cliente.create(nome: "VANESSA RODRIGUES", telefone: "996654506", email: "vancrodrigues@hotmail.com", como_conheceu: "INTERNET")
VERONICA = Cliente.create(nome: "VERONICA", telefone: "19996282603", email: "", como_conheceu: "DINA LELLIT")
VILMAEARLINDOMANOELA = Cliente.create(nome: "VILMA E ARLINDO - MANOELA", telefone: "988611690", email: "vilma@aevseguros.com.br", como_conheceu: "EDILAYNE FERRAZ")
VINICIUSDAFINE = Cliente.create(nome: "VINICIUS - DAFINE", telefone: "WHATS", email: "vinicius@lucimarpossari.com.br", como_conheceu: "LUCIMAR POSSARI")
VIRGINIALABARCA = Cliente.create(nome: "VIRGINIA LABARCA", telefone: "983829209", email: "vilabarca@gmail.com", como_conheceu: "PUBLICIDADE")
VIVIANCAMILAEMURILO = Cliente.create(nome: "VIVIAN - CAMILA E MURILO", telefone: "98177-4437", email: "vivian@vivianbatiston.com.br", como_conheceu: "PELO CLIENTE DA FAZENDA TRES AUGUSTUS")
VIVIANE = Cliente.create(nome: "VIVIANE", telefone: "13 988420299", email: "viviane.goncalves@msn.com ", como_conheceu: "YOUTUBE")
VIVIANMOTAJULIAEDANIEL = Cliente.create(nome: "VIVIAN MOTA - JULIA E DANIEL", telefone: "981833818", email: "WTZP", como_conheceu: "INDICAÇÃO DE CLIENTE")


#########################################
################ LOCAIS #################
#########################################
ITAPIRA = Local.create(nome: "ITAPIRA", endereco: "ITAPIRA", cidade: "Campinas", estado: "SP")
ROYALCLINETEFOCUSPRODUCOES = Local.create(nome: "ROYAL - CLINETE FOCUS PRODUÇÕES", endereco: "ROYAL - CLINETE FOCUS PRODUÇÕES", cidade: "Campinas", estado: "SP")
REDEVENTOSJAGUARIUNA = Local.create(nome: "RED EVENTOS - JAGUARIUNA", endereco: "RED EVENTOS - JAGUARIUNA", cidade: "Campinas", estado: "SP")
LAGOASANTARITA = Local.create(nome: "LAGOA SANTA RITA", endereco: "LAGOA SANTA RITA", cidade: "Campinas", estado: "SP")
ESPACODONAINES = Local.create(nome: "ESPAÇO DONA INES", endereco: "ESPAÇO DONA INES", cidade: "Campinas", estado: "SP")
HOTELPLAZA = Local.create(nome: "HOTEL PLAZA", endereco: "HOTEL PLAZA", cidade: "Campinas", estado: "SP")
CHATEAUDUSOLANOS = Local.create(nome: "CHATEAU DU SOLANOS", endereco: "CHATEAU DU SOLANOS", cidade: "Campinas", estado: "SP")
VILLAFLOR = Local.create(nome: "VILLA FLOR", endereco: "VILLA FLOR", cidade: "Campinas", estado: "SP")
LEBLANC = Local.create(nome: "LE BLANC", endereco: "LE BLANC", cidade: "Campinas", estado: "SP")
BOSCH = Local.create(nome: "BOSCH", endereco: "BOSCH", cidade: "Campinas", estado: "SP")
PORTALGIRASSOL = Local.create(nome: "PORTAL GIRASSOL", endereco: "PORTAL GIRASSOL", cidade: "Campinas", estado: "SP")
SOUZAS = Local.create(nome: "SOUZAS", endereco: "Av. Dona Julia da Conceição Alves, 608 Sousas ", cidade: "Campinas", estado: "SP")
CAMPINAS = Local.create(nome: "CAMPINAS", endereco: "CAMPINAS", cidade: "Campinas", estado: "SP")
FLORDELOTUS = Local.create(nome: "FLOR DE LOTUS", endereco: "FLOR DE LOTUS", cidade: "Campinas", estado: "SP")
ANGELINOS = Local.create(nome: "ANGELINOS", endereco: "ANGELINOS", cidade: "Campinas", estado: "SP")
HIPNOSE = Local.create(nome: "HIPNOSE", endereco: "HIPNOSE", cidade: "Campinas", estado: "SP")
ESPACOM_DIMOND = Local.create(nome: "ESPAÇO M (DIMOND)", endereco: "JUNDIAI - ESPAÇO M (DIMOND)", cidade: "Campinas", estado: "SP")
CHACARAPARAISO = Local.create(nome: "CHACARA PARAISO", endereco: "CHACARA PARAISO", cidade: "Campinas", estado: "SP")
ESPACOBARAO = Local.create(nome: "ESPAÇO BARAO", endereco: "ESPAÇO BARAO", cidade: "Campinas", estado: "SP")
swisspark = Local.create(nome: "swiss park", endereco: "swiss park", cidade: "Campinas", estado: "SP")
ALPHAVILLE = Local.create(nome: "ALPHAVILLE", endereco: "ALPHAVILLE", cidade: "Campinas", estado: "SP")
SALAOCONDOMINIO = Local.create(nome: "SALAO CONDOMINIO", endereco: "JUNDIAI - SALAO CONDOMINIO", cidade: "Campinas", estado: "SP")
POTPOURRITCLASSICO = Local.create(nome: "POT POURRIT CLASSICO", endereco: "POT POURRIT CLASSICO", cidade: "Campinas", estado: "SP")
QUINTADASBROMELIAS = Local.create(nome: "QUINTA DAS BROMELIAS", endereco: "QUINTA DAS BROMELIAS", cidade: "Campinas", estado: "SP")
BUFFETIMAGEMCAMPESTRE = Local.create(nome: "BUFFET IMAGEM CAMPESTRE", endereco: "BUFFET IMAGEM CAMPESTRE", cidade: "Campinas", estado: "SP")
SPAZIOTRAMONTI = Local.create(nome: "SPAZIO TRAMONTI", endereco: "SPAZIO TRAMONTI", cidade: "Campinas", estado: "SP")
ESPACOCAMBARA = Local.create(nome: "ESPAÇO CAMBARÁ", endereco: "ESPAÇO CAMBARÁ", cidade: "Campinas", estado: "SP")
SHOPINGGALERIA = Local.create(nome: "SHOPING GALERIA", endereco: "SHOPING GALERIA", cidade: "Campinas", estado: "SP")
DUASMARIAS = Local.create(nome: "DUAS MARIAS", endereco: "DUAS MARIAS", cidade: "Campinas", estado: "SP")
ESPACOSUPREMO = Local.create(nome: "ESPAÇO SUPREMO", endereco: "ESPAÇO SUPREMO", cidade: "Campinas", estado: "SP")
IDEIAS3 = Local.create(nome: "3 IDEIAS", endereco: "3 IDEIAS", cidade: "Campinas", estado: "SP")
FLORESTAPARKCAMPINAS = Local.create(nome: "FLORESTA PARK CAMPINAS", endereco: "FLORESTA PARK CAMPINAS", cidade: "Campinas", estado: "SP")
ESPACOHIBISCUSPAULINIA = Local.create(nome: "ESPAÇO HIBISCUS PAULÍNIA", endereco: "ESPAÇO HIBISCUS PAULÍNIA", cidade: "Campinas", estado: "SP")
SERRANEGRADONAELZA = Local.create(nome: "SERRA NEGRA DONA ELZA", endereco: "SERRA NEGRA DONA ELZA", cidade: "Campinas", estado: "SP")
ESPACOSONHOREALIZADO = Local.create(nome: "ESPAÇO SONHO REALIZADO", endereco: "MONTE MOR - ESPAÇO SONHO REALIZADO", cidade: "Campinas", estado: "SP")
LANUIT = Local.create(nome: "LA NUIT", endereco: "LA NUIT", cidade: "Campinas", estado: "SP")
CULTURADECAMPO = Local.create(nome: "CULTURA DE CAMPO", endereco: "CULTURA DE CAMPO", cidade: "Campinas", estado: "SP")
VIAAPPIA = Local.create(nome: "VIA APPIA", endereco: "VIA APPIA", cidade: "Campinas", estado: "SP")
BUFFETIMAGEMCONTEMPORANEO = Local.create(nome: "BUFFET IMAGEM CONTEMPORANEO", endereco: "BUFFET IMAGEM CONTEMPORANEO", cidade: "Campinas", estado: "SP")
ANGELINOSOUMONETEVENTOS = Local.create(nome: "ANGELINOS OU MONET EVENTOS", endereco: "ANGELINOS OU MONET EVENTOS", cidade: "Campinas", estado: "SP")
VALEDOSSONHOS = Local.create(nome: "VALE DOS SONHOS", endereco: "VALE DOS SONHOS", cidade: "Campinas", estado: "SP")
VILADELIKATESSEN = Local.create(nome: "VILA DELIKATESSEN", endereco: "VILA DELIKATESSEN", cidade: "Campinas", estado: "SP")
ITATIBASERRADOSCOCAIS = Local.create(nome: "ITATIBA SERRA DOS COCAIS", endereco: "ITATIBA SERRA DOS COCAIS", cidade: "Campinas", estado: "SP")
JACUTINGA = Local.create(nome: "JACUTINGA", endereco: "JACUTINGA", cidade: "Campinas", estado: "SP")
PAULINIAHIBISCUS = Local.create(nome: "PAULINIA HIBISCUS", endereco: "PAULINIA HIBISCUS", cidade: "Campinas", estado: "SP")
FAZENDADASCABRAS = Local.create(nome: "FAZENDA DAS CABRAS", endereco: "FAZENDA DAS CABRAS", cidade: "Campinas", estado: "SP")
FLORIADAEVENTOS = Local.create(nome: "FLORIADA EVENTOS", endereco: "FLORIADA EVENTOS", cidade: "Campinas", estado: "SP")
BELMONTEEVENTOS = Local.create(nome: "BELMONTE EVENTOS", endereco: "BELMONTE EVENTOS", cidade: "Campinas", estado: "SP")
ESPACOFOLHAEAGUA = Local.create(nome: "ESPAÇO FOLHA E AGUA", endereco: "ESPAÇO FOLHA E AGUA", cidade: "Campinas", estado: "SP")
VILASANSU = Local.create(nome: "VILA SANSU", endereco: "VILA SANSU", cidade: "Campinas", estado: "SP")
ALTODASPALMEIRAS = Local.create(nome: "ALTO DAS PALMEIRAS", endereco: "ALTO DAS PALMEIRAS", cidade: "Campinas", estado: "SP")
BUFFETEVENTUSPIRACICABA = Local.create(nome: "BUFFET EVENTUS - PIRACICABA", endereco: "BUFFET EVENTUS - PIRACICABA", cidade: "Campinas", estado: "SP")
ESPACODOISIRMAOS = Local.create(nome: "ESPAÇO DOIS IRMAOS", endereco: "ESPAÇO DOIS IRMAOS", cidade: "Campinas", estado: "SP")
BUFFETIMAGEM = Local.create(nome: "BUFFET IMAGEM", endereco: "BUFFET IMAGEM", cidade: "Campinas", estado: "SP")
VALINHOS = Local.create(nome: "VALINHOS", endereco: "VALINHOS", cidade: "Campinas", estado: "SP")
KRATOS = Local.create(nome: "KRATOS", endereco: "KRATOS", cidade: "Campinas", estado: "SP")
TENISCLUBE = Local.create(nome: "TENIS CLUBE", endereco: "TENIS CLUBE", cidade: "Campinas", estado: "SP")
MONTECASTELO = Local.create(nome: "MONTE CASTELO", endereco: "MONTE CASTELO", cidade: "Campinas", estado: "SP")
ESPACOTERRAZZA = Local.create(nome: "ESPAÇO TERRAZZA", endereco: "ESPAÇO TERRAZZA", cidade: "Campinas", estado: "SP")
VILAMANRESA = Local.create(nome: "VILA MANRESA", endereco: "VILA MANRESA", cidade: "Campinas", estado: "SP")
ESPACOBELAVISTA = Local.create(nome: "ESPAÇO BELA VISTA", endereco: "ESPAÇO BELA VISTA", cidade: "Campinas", estado: "SP")
ESPACOMEDIEVALCASTELODOSVINHAIS = Local.create(nome: "ESPAÇO MEDIEVAL - CASTELO DOS VINHAIS", endereco: "ESPAÇO MEDIEVAL - CASTELO DOS VINHAIS", cidade: "Campinas", estado: "SP")
ESPACOSANTAESPLENDORROOM = Local.create(nome: "ESPAÇO SANTA ESPLENDOR ROOM", endereco: "ESPAÇO SANTA ESPLENDOR ROOM", cidade: "Campinas", estado: "SP")
HELENOFESTAS = Local.create(nome: "HELENO FESTAS", endereco: "HELENO FESTAS", cidade: "Campinas", estado: "SP")
CASAPALMEIRA = Local.create(nome: "CASA PALMEIRA", endereco: "CASA PALMEIRA", cidade: "Campinas", estado: "SP")
RANCHOAVEIRO = Local.create(nome: "RANCHO AVEIRO", endereco: "RANCHO AVEIRO", cidade: "Campinas", estado: "SP")
ESPACOVILAVERDE = Local.create(nome: "ESPAÇO VILA VERDE", endereco: "ESPAÇO VILA VERDE", cidade: "Campinas", estado: "SP")
PEDREIRAQUINTADOLAGO = Local.create(nome: "PEDREIRA - QUINTA DO LAGO", endereco: "PEDREIRA - QUINTA DO LAGO", cidade: "Campinas", estado: "SP")
GUANABARA = Local.create(nome: "GUANABARA", endereco: "GUANABARA", cidade: "Campinas", estado: "SP")
THEROYALIMPERIAL = Local.create(nome: "THE ROYAL  - IMPERIAL", endereco: "THE ROYAL  - IMPERIAL", cidade: "Campinas", estado: "SP")
FAZENDALAGEADO = Local.create(nome: "FAZENDA LAGEADO", endereco: "FAZENDA LAGEADO", cidade: "Campinas", estado: "SP")
BUFFETIMAGEMMEDIEVAL = Local.create(nome: "BUFFET IMAGEM MEDIEVAL", endereco: "BUFFET IMAGEM MEDIEVAL", cidade: "Campinas", estado: "SP")
BOATEHIPICA = Local.create(nome: "BOATE HIPICA", endereco: "BOATE HIPICA", cidade: "Campinas", estado: "SP")
ESPACO55 = Local.create(nome: "ESPAÇO 55", endereco: "INDAIATUBA - ESPAÇO 55", cidade: "Campinas", estado: "SP")
VILLAHARMONIA = Local.create(nome: "VILLA HARMONIA", endereco: "VILLA HARMONIA", cidade: "Campinas", estado: "SP")
CHACARARECANTODOSPASSAROS = Local.create(nome: "CHACARA RECANTO DOS PASSAROS", endereco: "CHACARA RECANTO DOS PASSAROS", cidade: "Campinas", estado: "SP")
FONTESAOPAULO = Local.create(nome: "FONTE SÃO PAULO", endereco: "FONTE SÃO PAULO", cidade: "Campinas", estado: "SP")
HARASDAFAMILIA = Local.create(nome: "HARAS DA FAMILIA", endereco: "HARAS DA FAMILIA", cidade: "Campinas", estado: "SP")
LEPARTIE = Local.create(nome: "LE PARTIE", endereco: "LE PARTIE", cidade: "Campinas", estado: "SP")
THEROYAL = Local.create(nome: "THE ROYAL", endereco: "THE ROYAL", cidade: "Campinas", estado: "SP")
HIPICASOCIAL = Local.create(nome: "HIPICA SOCIAL", endereco: "HIPICA SOCIAL", cidade: "Campinas", estado: "SP")
BUFFETCLIMATROPICAL = Local.create(nome: "BUFFET CLIMA TROPICAL", endereco: "BUFFET CLIMA TROPICAL", cidade: "Campinas", estado: "SP")
VILASAOVITO = Local.create(nome: "VILA SÃO VITO", endereco: "VILA SÃO VITO", cidade: "Campinas", estado: "SP")
AGUASDELINDOIA = Local.create(nome: "AGUAS DE LINDOIA", endereco: "AGUAS DE LINDOIA", cidade: "Campinas", estado: "SP")
VERDANOEVENTOS = Local.create(nome: "VERDANO EVENTOS", endereco: "VERDANO EVENTOS", cidade: "Campinas", estado: "SP")
CAMBARAFESTAS = Local.create(nome: "CAMBARA FESTAS", endereco: "CAMBARA FESTAS", cidade: "Campinas", estado: "SP")
HOTELVITORIA = Local.create(nome: "HOTEL VITORIA", endereco: "HOTEL VITORIA", cidade: "Campinas", estado: "SP")
WETNWILD = Local.create(nome: "WETN WILD", endereco: "WETN WILD", cidade: "Campinas", estado: "SP")



#########################################
################ EVENTOS ################
#########################################
evento1 = Evento.create(cliente_id: DERIO.id, data_evento: '13-01-2018 00:00', tipo_evento_id:CORPORATIVO.id, evento_status:1, local_id: ITAPIRA.id)
evento1.proposta.create(descricao: '8683')

Evento.create(cliente_id: JACKFOCUSPRODUCOES.id, data_evento: '17-01-2018 00:00', tipo_evento_id:CORPORATIVO.id, evento_status:4, local_id: ROYALCLINETEFOCUSPRODUCOES.id)
Evento.create(cliente_id: HEBERFOTOSGABRIEL.id, data_evento: '20-01-2018 22:00', tipo_evento_id:FORMATURA.id, evento_status:4, local_id: REDEVENTOSJAGUARIUNA.id, quantidade_horas: 6)
Evento.create(cliente_id: ANNEELUCAS.id, data_evento: '20-01-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: LAGOASANTARITA.id)
Evento.create(cliente_id: DJKUKAVICENTIN.id, data_evento: '27-01-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: ESPACODONAINES.id, quantidade_horas: 18)
Evento.create(cliente_id: KARINAFUNARI.id, data_evento: '01-02-2018 00:00', tipo_evento_id:CORPORATIVO.id, evento_status:1, local_id: HOTELPLAZA.id)
Evento.create(cliente_id: HELENAGUERRA.id, tipo_evento_id:CASAMENTO.id, evento_status:2)
Evento.create(cliente_id: VIVIANCAMILAEMURILO.id, data_evento: '03-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CHATEAUDUSOLANOS.id)
Evento.create(cliente_id: SONIA.id, data_evento: '03-02-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: VILLAFLOR.id)
Evento.create(cliente_id: FLAVIACANTUSIOSTEPHANIEEEDUARDO.id, data_evento: '03-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LEBLANC.id)
Evento.create(cliente_id: MARIAVITORIA.id, data_evento: '04-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BOSCH.id)
Evento.create(cliente_id: FLAVIACANTUSIOALINEELUCAS.id, data_evento: '10-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PORTALGIRASSOL.id)
Evento.create(cliente_id: CASSIATAYRINE.id, data_evento: '10-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: SOUZAS.id)
Evento.create(cliente_id: FERNANDA1.id, data_evento: '12-02-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '23-02-2018 00:00', tipo_evento_id:FORMATURA.id, evento_status:1, local_id: FLORDELOTUS.id)
Evento.create(cliente_id: FLAVIADIAS.id, data_evento: '06-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: CARINAEANTONY.id, data_evento: '03-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:5, local_id: HIPNOSE.id)
Evento.create(cliente_id: JULIADEOLIVEIRA.id, data_evento: '03-03-2018 00:00', tipo_evento_id:FORMATURA.id, evento_status:1, local_id: ESPACOM_DIMOND.id, observacao: 'INDICAÇÃO DE UMA NOIVAM QUE CASOU NO LOCAL')
Evento.create(cliente_id: GABRIELA.id, data_evento: '09-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:1, local_id: ANGELINOS.id, observacao: 'THAISA AGUAS DE LINDOIA')
Evento.create(cliente_id: SILVIA.id, data_evento: '09-03-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CHACARAPARAISO.id)
Evento.create(cliente_id: DANIELA1.id, data_evento: '10-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:1, local_id: ESPACOBARAO.id)
Evento.create(cliente_id: KENNIASILVA.id, data_evento: '10-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:3, local_id: swisspark.id)
Evento.create(cliente_id: RITAEGERALDO.id, data_evento: '16-03-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:5, local_id: ESPACOBARAO.id)
Evento.create(cliente_id: CAROLINEBRITO.id, data_evento: '17-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: FLAVIACANTUSIOBEATRIZEFABRICIO.id, data_evento: '17-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ALPHAVILLE.id)
Evento.create(cliente_id: JULIA.id, data_evento: '02-02-2018 00:00', tipo_evento_id:ANIVERSARIO.id, evento_status:1, local_id: SALAOCONDOMINIO.id)
Evento.create(cliente_id: LETICIACRISTINACARAZATTOETHIAGOSOARESSILVA.id, data_evento: '23-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: POTPOURRITCLASSICO.id)
Evento.create(cliente_id: LUCIANAROCHASOARES.id, data_evento: '23-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: FERNANDA2.id, data_evento: '24-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PORTALGIRASSOL.id)
Evento.create(cliente_id: JULIANACAMPOS.id, data_evento: '24-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOBARAO.id)
Evento.create(cliente_id: SULAMITAFERREIRAPICCOLIeMATHEUS.id, data_evento: '30-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id)
Evento.create(cliente_id: VILMAEARLINDOMANOELA.id, data_evento: '06-04-2018 21:00', tipo_evento_id:DEBUTANTE.id, evento_status:4, local_id: BUFFETIMAGEMCAMPESTRE.id, quantidade_horas: 6)
Evento.create(cliente_id: LEILAHPASSOS.id, data_evento: '07-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: SPAZIOTRAMONTI.id, quantidade_horas: 7)
Evento.create(cliente_id: FLAVIACANTUSIOGIOVANAEGUILHERME.id, data_evento: '07-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ESPACOCAMBARA.id)
Evento.create(cliente_id: THATIANEFANTINI.id, data_evento: '07-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: SHOPINGGALERIA.id)
Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '08-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id, observacao: 'Noivos: MAINÁ E VINICIUS')
Evento.create(cliente_id: RENATA2MEVENTOSHELOISAEFELIPE.id, data_evento: '14-04-2018 17:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: DUASMARIAS.id, quantidade_horas: 8)
Evento.create(cliente_id: NADIAEGUSTAVO.id, data_evento: '14-04-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: ESPACOBARAO.id, quantidade_horas: 6,)
Evento.create(cliente_id: MARIANAJACOBERENATO.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ESPACOSUPREMO.id)
Evento.create(cliente_id: JULIAISABELCURY.id, data_evento: '14-04-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: IDEIAS3.id)
Evento.create(cliente_id: FERNANDOECAROL.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORESTAPARKCAMPINAS.id)
Evento.create(cliente_id: JOYCESANTOPEDRO.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: CLELIAMDOPRADO.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOHIBISCUSPAULINIA.id)
Evento.create(cliente_id: MARIANA.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: SERRANEGRADONAELZA.id)
Evento.create(cliente_id: LETICIAEJOAOPAULO.id, data_evento: '21-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: BUFFETIMAGEMCAMPESTRE.id)
Evento.create(cliente_id: CARLAANALUISA.id, data_evento: '21-04-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:5, local_id: ANGELINOS.id)
Evento.create(cliente_id: DANIELLIARAUJOCOSTA.id, data_evento: '21-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSONHOREALIZADO.id)
Evento.create(cliente_id: DANIELA2.id, data_evento: '21-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
Evento.create(cliente_id: LIA.id, data_evento: '21-04-2018 00:00', tipo_evento_id:BODAS.id, evento_status:1, local_id: CULTURADECAMPO.id)
Evento.create(cliente_id: CLAUDIATHIAGOHADI.id, data_evento: '27-04-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: VIAAPPIA.id)
Evento.create(cliente_id: BRUNAMARCELAEDIEGO.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id)
Evento.create(cliente_id: VIRGINIALABARCA.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORESTAPARKCAMPINAS.id)
Evento.create(cliente_id: JESSICA1.id, data_evento: '29-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCONTEMPORANEO.id)
Evento.create(cliente_id: RICARDOEJULIANA.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOSOUMONETEVENTOS.id)
Evento.create(cliente_id: ALINE.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VALEDOSSONHOS.id)
Evento.create(cliente_id: TULIO.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILADELIKATESSEN.id)
Evento.create(cliente_id: VALDICEABREU.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ITATIBASERRADOSCOCAIS.id)
Evento.create(cliente_id: THIAGOARTMIDIA.id, data_evento: '05-05-2018 00:00', tipo_evento_id:LOCACAO.id, evento_status:1, local_id: JACUTINGA.id)
Evento.create(cliente_id: LAIS.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
Evento.create(cliente_id: CAMILAEBRUNO.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PAULINIAHIBISCUS.id)
Evento.create(cliente_id: ROBERTFELDER.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FAZENDADASCABRAS.id)
Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '11-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id, observacao: 'Noivos: ISABELA E DANILO')
Evento.create(cliente_id: THAINAEHEINRIQUE.id, data_evento: '19-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORIADAEVENTOS.id)
Evento.create(cliente_id: LUCASEJULIANA.id, data_evento: '19-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BELMONTEEVENTOS.id)
Evento.create(cliente_id: JULIANAEEVERSON.id, data_evento: '26-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
Evento.create(cliente_id: NATALIAEGUILHERME.id, data_evento: '26-05-2018 19:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: ESPACOFOLHAEAGUA.id, quantidade_horas: 7)
Evento.create(cliente_id: ANACAROLINA.id, data_evento: '27-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILASANSU.id)
Evento.create(cliente_id: PRISCILAEJOAO.id, data_evento: '02-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id)
Evento.create(cliente_id: GABRIELAERODRIGO.id, data_evento: '08-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ALTODASPALMEIRAS.id, observacao: 'INDICACAO DE UM AMIGO QUE VAI FAZER A FESTA CONOSCO MARCINHO QUE TOCOU')
Evento.create(cliente_id: FERNANDOASSISePATRICIA.id, data_evento: '09-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ITATIBASERRADOSCOCAIS.id)
Evento.create(cliente_id: LUCIMARPOSSARI.id, data_evento: '09-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ITATIBASERRADOSCOCAIS.id)
Evento.create(cliente_id: CAROLINAPASSARELLI.id, data_evento: '16-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETEVENTUSPIRACICABA.id)
Evento.create(cliente_id: ROSANALEITE.id, data_evento: '16-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACODOISIRMAOS.id)
Evento.create(cliente_id: PATRICIA.id, data_evento: '30-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSUPREMO.id)
Evento.create(cliente_id: ANACLAUDIA.id, data_evento: '07-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEM.id)
Evento.create(cliente_id: THAISPAOLA.id, data_evento: '07-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VALINHOS.id)
Evento.create(cliente_id: AMANDADEPAOLA.id, data_evento: '07-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: KRATOS.id)
Evento.create(cliente_id: GABRIELASANTANA.id, data_evento: '08-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: FLAVIACANTUSIOERIKAEMAURICIO.id, data_evento: '13-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: VIVIANMOTAJULIAEDANIEL.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: TENISCLUBE.id)
Evento.create(cliente_id: MARCELOAMARAL.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LAGOASANTARITA.id)
Evento.create(cliente_id: JULIANAGURIAN.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: ERIKAKAMPOS.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: ALEXANDREFORA.id, data_evento: '21-07-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:4)
Evento.create(cliente_id: FLAVIOCRUZ.id, data_evento: '21-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: BARBARASOUZA.id, data_evento: '27-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: MONTECASTELO.id)
Evento.create(cliente_id: SALETEMICHELEEFLAVIO.id, data_evento: '28-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOTERRAZZA.id, observacao: 'ta com vera cerimonial e aldo silvestre')
Evento.create(cliente_id: CAROLINACREPALDIETHALLES.id, data_evento: '11-08-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: VILAMANRESA.id, quantidade_horas: 6)
Evento.create(cliente_id: RAPHAELALVEZ.id, data_evento: '11-08-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: ESPACOBELAVISTA.id)
Evento.create(cliente_id: PAULA.id, data_evento: '17-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOMEDIEVALCASTELODOSVINHAIS.id)
Evento.create(cliente_id: ARIANEEVALENTIN.id, data_evento: '18-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: NATALIEBRUNO.id, data_evento: '18-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSANTAESPLENDORROOM.id)
Evento.create(cliente_id: NEMELLYERAFAEL.id, data_evento: '15-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: HELENOFESTAS.id)
Evento.create(cliente_id: JULIOOHIRA.id, data_evento: '27-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
Evento.create(cliente_id: NICOLEKARINAAMAE.id, data_evento: '25-08-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:5, local_id: CASAPALMEIRA.id)
Evento.create(cliente_id: TAYNA.id, data_evento: '06-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: RANCHOAVEIRO.id)
Evento.create(cliente_id: LIDIANEBASCHIERA.id, data_evento: '06-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSUPREMO.id)
Evento.create(cliente_id: VANESSAFACCHIN.id, data_evento: '08-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOVILAVERDE.id)
Evento.create(cliente_id: DEBORA.id, data_evento: '08-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ESPACOSUPREMO.id)
Evento.create(cliente_id: PAULORBERNARDES.id, data_evento: '15-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PEDREIRAQUINTADOLAGO.id)
Evento.create(cliente_id: JESSICA2.id, data_evento: '15-09-2018 12:20:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: GUANABARA.id)
Evento.create(cliente_id: MARINAEANDRE.id, data_evento: '15-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: MONTECASTELO.id)
Evento.create(cliente_id: JULIANACESARGRANJA.id, data_evento: '22-09-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: LANUIT.id, quantidade_horas: 7)
Evento.create(cliente_id: VINICIUSDAFINE.id, data_evento: '22-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VIAAPPIA.id)
Evento.create(cliente_id: NATHALIASUNIGAEFERNANDO.id, data_evento: '12-10-2018 21:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: LANUIT.id, quantidade_horas: 6)
Evento.create(cliente_id: MAYRABONIN.id, data_evento: '12-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: THEROYALIMPERIAL.id)
Evento.create(cliente_id: ALDOSILVESTRE.id, data_evento: '12-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VIAAPPIA.id)
Evento.create(cliente_id: ALESSANDRAEMARCIO.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: GUANABARA.id)
Evento.create(cliente_id: FLAVIACANTUSIORAFAELAELUCAS.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FAZENDALAGEADO.id)
Evento.create(cliente_id: TALITAECLEVERTON.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2, local_id: VIAAPPIA.id)
Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PORTALGIRASSOL.id, observacao: 'Noivos: AMANDA E PAULO')
Evento.create(cliente_id: BRUNAOLIVEIRA.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILLAFLOR.id)
Evento.create(cliente_id: ERICDEMOURABRAMBILA.id, data_evento: '19-10-2018 00:00', tipo_evento_id:ANIVERSARIO.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: PALOMAERODRIGOCARLAROSSINI.id, data_evento: '20-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: VIAAPPIA.id)
Evento.create(cliente_id: RENATASARITAEEDUARDO.id, data_evento: '20-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: DUASMARIAS.id)
Evento.create(cliente_id: ISABELACAUMEPAULO.id, data_evento: '20-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMMEDIEVAL.id)
Evento.create(cliente_id: ANAFLAVIAEJEFERSON.id, data_evento: '03-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORIADAEVENTOS.id)
Evento.create(cliente_id: PATRICIATENORIO.id, data_evento: '09-11-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:3, local_id: BOATEHIPICA.id)
Evento.create(cliente_id: ANE.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: KRATOS.id)
Evento.create(cliente_id: RICARDODOPRADOLAIA.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
Evento.create(cliente_id: PAULOHENRIQUEDASILVA.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: FELIPEMOREIRA.id, data_evento: '11-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMMEDIEVAL.id)
Evento.create(cliente_id: NATALIA.id, data_evento: '15-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
Evento.create(cliente_id: LARISSAHADASSAELUCIANO.id, data_evento: '15-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2, local_id: ALTODASPALMEIRAS.id)
Evento.create(cliente_id: FABRINARIBEIRO.id, data_evento: '15-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACO55.id)
Evento.create(cliente_id: PRISCILA.id, data_evento: '16-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: KRATOS.id)
Evento.create(cliente_id: BrunaSumiregi.id, data_evento: '18-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: VILLAHARMONIA.id)
Evento.create(cliente_id: KARINENICOLETI.id, data_evento: '24-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: MONTECASTELO.id)
Evento.create(cliente_id: RAQUELEGUILHERME.id, data_evento: '24-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: ANAPAULACASALMARINAEPEDRO.id, data_evento: '24-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ALTODASPALMEIRAS.id)
Evento.create(cliente_id: ANDRESSA.id, data_evento: '24-11-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CHACARARECANTODOSPASSAROS.id)
Evento.create(cliente_id: DAIANEARAUJO.id, data_evento: '01-12-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FONTESAOPAULO.id)
Evento.create(cliente_id: BARBARAELUCAS.id, data_evento: '01-12-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2, local_id: HARASDAFAMILIA.id)
Evento.create(cliente_id: GLAUCIAERENAN.id, data_evento: '19-01-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LEPARTIE.id)
Evento.create(cliente_id: MARCELA.id, data_evento: '26-01-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: THEROYAL.id)
Evento.create(cliente_id: ANACAROLINAELUIZ.id, data_evento: '02-03-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: GUANABARA.id)
Evento.create(cliente_id: CYBELLE.id, data_evento: '03-03-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOMEDIEVALCASTELODOSVINHAIS.id)
Evento.create(cliente_id: DANIELLIRAMOSTONHAI.id, data_evento: '13-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
Evento.create(cliente_id: BRUNAEPEDRO.id, data_evento: '13-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: HIPICASOCIAL.id)
Evento.create(cliente_id: JAQUELINE.id, data_evento: '23-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: BUFFETCLIMATROPICAL.id)
Evento.create(cliente_id: CAROLINEEJOAO.id, data_evento: '27-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILASAOVITO.id)
Evento.create(cliente_id: TATIANA.id, data_evento: '09-06-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
Evento.create(cliente_id: VIVIANE.id, data_evento: '22-06-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: AGUASDELINDOIA.id)
Evento.create(cliente_id: FLAVIAERICAEMAURICIO.id, data_evento: '13-07-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: ELLEN.id, data_evento: '23-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMMEDIEVAL.id)
Evento.create(cliente_id: CAMILA.id, data_evento: '14-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LAGOASANTARITA.id)
Evento.create(cliente_id: KELMA.id, data_evento: '16-09-2019 00:00', tipo_evento_id:FORMATURA.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: ELIZABETHNEGRAES.id, data_evento: '23-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: THAISCAROLINEERENAN.id, data_evento: '28-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BOSCH.id)
Evento.create(cliente_id: JAQUELINERAPHAELZOTARELI.id, data_evento: '05-10-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VERDANOEVENTOS.id)
Evento.create(cliente_id: VANESSARODRIGUES.id, data_evento: '21-06-2019 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CAMPINAS.id)
Evento.create(cliente_id: KARENEDANILO.id, data_evento: '23-08-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
Evento.create(cliente_id: LIVIADESOUZARODRIGUES.id, data_evento: ' 13-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: ARTHUR.id, tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: RANCHOAVEIRO.id)
Evento.create(cliente_id: MAISAMOREIRA.id, data_evento: '03-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMBARAFESTAS.id)
Evento.create(cliente_id: THAYNARA.id, data_evento: '04-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
Evento.create(cliente_id: ELAINE.id, data_evento: '01-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
Evento.create(cliente_id: MARGARETHBARROS.id, tipo_evento_id:FORMATURA.id, evento_status:1, local_id: HOTELVITORIA.id)
Evento.create(cliente_id: BIANCACLARA.id, data_evento: '22-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
Evento.create(cliente_id: NATALIAPOLONICORREA.id, data_evento: '28-07-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: MILENACAMPOS.id, data_evento: '22-12-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: CAMILAPICCELICHOQUETA.id, data_evento: '28-10-2027 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: LIVIACASTRO.id, data_evento: '14-07-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: JESSICAGEREMIAS.id, data_evento: '20-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2, observacao: 'INDICAÇAO DE UM PROFISSIONAL - PELA MAE CLAUIDIA ASSIONE')
Evento.create(cliente_id: MARGARETHBARROS.id, tipo_evento_id:FORMATURA.id, evento_status:1, local_id: WETNWILD.id)
Evento.create(cliente_id: NAYARAMACANOSSO.id, data_evento: '18-08-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: TANIAMARIAFORTUNATO.id, data_evento: '13-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: VERONICA.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
Evento.create(cliente_id: CAMILAEFABIO.id, data_evento: '20-05-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2, observacao: 'CLIENTE NÃO ESTA NO MAILING')
Evento.create(cliente_id: THAISEPEDRO.id, data_evento: '20-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: THAINAEHENRIQUE.id, data_evento: '19-05-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: LARISSAEVINICIUS.id, data_evento: '24-11-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: REBECAEFELIPE.id, data_evento: '08-09-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
Evento.create(cliente_id: ROBERTAEKAIO.id, data_evento: '18-08-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)