# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

###########################################################################################################################
#################################################### TIPOS DE EVENTOS #####################################################
###########################################################################################################################
CORPORATIVO = TipoEvento.create( descricao: "CORPORATIVO")
FORMATURA = TipoEvento.create( descricao: "FORMATURA")
CASAMENTO = TipoEvento.create( descricao: "CASAMENTO")
DEBUTANTE = TipoEvento.create( descricao: "DEBUTANTE")
ANIVERSARIO = TipoEvento.create( descricao: "ANIVERSARIO")
BODAS = TipoEvento.create( descricao: "BODAS")
LOCACAO = TipoEvento.create( descricao: "LOCAÇÃO")
OUTROS = TipoEvento.create( descricao: "OUTROS")


###########################################################################################################################
######################################################## CLIENTES #########################################################
###########################################################################################################################
ALDOSILVESTRE = Cliente.create(nome: "ALDO SILVESTRE", telefone: "-", email: "-", como_conheceu: "ALDO SILVESTRE")
ALESSANDRAEMARCIO = Cliente.create(nome: "ALESSANDRA E MARCIO", telefone: "999391981", email: "legomes456@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
ALEXANDREFORA = Cliente.create(nome: "ALEXANDRE FORA", telefone: "-", email: "", como_conheceu: "Não informado")
ALINE = Cliente.create(nome: "ALINE", telefone: "19 98851-8722", email: "cerimonialalinebeatriz@gmail.com", como_conheceu: "cerimonial aline beatriz")
AMANDADEPAOLA = Cliente.create(nome: "AMANDA DE PAOLA", telefone: "992997826", email: "amandadepaola@hotmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
ANACAROLINA = Cliente.create(nome: "ANA CAROLINA", telefone: "15 99148-2728", email: "carolcacace@hotmail.com ", como_conheceu: "INDICAÇÃO DE CLIENTE")
ANACAROLINAELUIZ = Cliente.create(nome: "ANA CAROLINA E LUIZ", telefone: "993088040", email: "anacarolina_mgomes@outlook.com", como_conheceu: "MALU PAN")
ANACLAUDIA = Cliente.create(nome: "ANA CLAUDIA", telefone: "981637165", email: "cryedinha@hotmail.com", como_conheceu: "FACEBOOK")
ANAFLAVIAEJEFERSON = Cliente.create(nome: "ANA FLAVIA E JEFERSON", telefone: "13996627557", email: "anaflaviavet92@outlook.com", como_conheceu: "FEIRA BUFFET CANOA")
ANAPAULACASALMARINAEPEDRO = Cliente.create(nome: "ANA PAULA - CASAL MARINA E PEDRO", telefone: "992871064", email: "apl.aranha@gmail.com", como_conheceu: "Não informado")
ANDRESSA = Cliente.create(nome: "ANDRESSA", telefone: "988221220", email: "15anosnanda@gmail.com", como_conheceu: "INDICAÇAO DE UM PROFISSIONAL")
ANE = Cliente.create(nome: "ANE", telefone: "11 99606-7977", email: "anecarol.p@gmail.com", como_conheceu: "Não informado")
ANNEELUCAS = Cliente.create(nome: "ANNE E LUCAS", telefone: "11981880355", email: "anne.layze@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
ARIANEEVALENTIN = Cliente.create(nome: "ARIANE E VALENTIN", telefone: "994848439", email: "ary-fisio@hotmail.com", como_conheceu: "ANGELINOS")
ARTHUR = Cliente.create(nome: "ARTHUR", telefone: "991796364", email: "penteado.arthur@gmail.com", como_conheceu: "Não informado")
BARBARAELUCAS = Cliente.create(nome: "BARBARA E LUCAS", telefone: "996855684", email: "barbara_tebalde@hotmail.com", como_conheceu: "FEIRA CIRQUITO DAS AGUAS")
BARBARASOUZA = Cliente.create(nome: "BARBARA SOUZA", telefone: "11 96242-1210 ", email: "barbara.souza@semparar.net, barbaraejeison@gmail.com", como_conheceu: "Não informado")
BIANCACLARA = Cliente.create(nome: "BIANCA CLARA ", telefone: "99696-3568                        ", email: "", como_conheceu: "DINA LELLIT")
BRUNAEPEDRO = Cliente.create(nome: "BRUNA E PEDRO", telefone: "997636394", email: "bruna_ravara@hotmail.com", como_conheceu: "FACEBOOK")
BRUNAMARCELAEDIEGO = Cliente.create(nome: "BRUNA - (MARCELA E DIEGO)", telefone: "33874316", email: "eventos@parperfeitocerimonial.com.br", como_conheceu: "PAR PERFEITO")
BRUNAOLIVEIRA = Cliente.create(nome: "BRUNA OLIVEIRA", telefone: "91522199", email: "brunaeaoliveira@gmail.com", como_conheceu: "INDICAÇAO DE UM PROFISSIONAL")
BrunaSumiregi = Cliente.create(nome: "Bruna Sumiregi", telefone: "-", email: "-", como_conheceu: "CASAMENTOS.COM.BR")
CAMILA = Cliente.create(nome: "CAMILA", telefone: "11 98735-0069", email: "cc.arna@ig.com.br", como_conheceu: "CASAMENTOS.COM.BR")
CAMILAEBRUNO = Cliente.create(nome: "CAMILA E BRUNO", telefone: "NÃO DEIXOU", email: "camilaebruno050518@gmail.com", como_conheceu: "Não informado")
CAMILAEFABIO = Cliente.create(nome: "CAMILA E FABIO  ", telefone: "-", email: "camilaefabio1205@gmail.com", como_conheceu: "RENATA 2M EVENTOS")
CAMILAPICCELICHOQUETA = Cliente.create(nome: "CAMILA PICCELI CHOQUETA", telefone: "998702985", email: "", como_conheceu: "DINA LELLIT")
CARINAEANTONY = Cliente.create(nome: "CARINA E ANTONY", telefone: "992184321 OU 991516363", email: "cssolon@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
CARLAANALUISA = Cliente.create(nome: "CARLA - ANA LUISA", telefone: "19 99339-0523", email: "andrechukma@yahoo.com.br", como_conheceu: "ANGELINOS")
CAROLINACREPALDIETHALLES = Cliente.create(nome: "CAROLINA CREPALDI E THALLES", telefone: "3329-0422", email: "ca_ermani@hotmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
CAROLINAPASSARELLI = Cliente.create(nome: "CAROLINA PASSARELLI", telefone: "11981051584", email: "carolinapassarelli@uol.com.br", como_conheceu: "INTERNET")
CAROLINEBRITO = Cliente.create(nome: "CAROLINE BRITO", telefone: "32966259", email: "carol.brito@hotmail.com", como_conheceu: "INTERNET")
CAROLINEEJOAO = Cliente.create(nome: "CAROLINE E JOAO", telefone: "991760198", email: "caa.felix@hotmail.com", como_conheceu: "QUEMCASAQUERSITE")
CASSIATAYRINE = Cliente.create(nome: "CASSIA TAYRINE", telefone: "994787808", email: "tayrinecassia@gmail.com", como_conheceu: "INTERNET")
CLAUDIATHIAGOHADI = Cliente.create(nome: "CLAUDIA THIAGO HADI", telefone: "WHATS", email: "thiago@thiagohadi.com.br", como_conheceu: "THIAGO HADI")
CLELIAMDOPRADO = Cliente.create(nome: "CLÉLIA M DO PRADO ", telefone: "19-974152464", email: "mayaraprado62@gmail.com", como_conheceu: "REDE SOCIAL")
CYBELLE = Cliente.create(nome: "CYBELLE", telefone: "991081273", email: "manzzi_feijo@yahoo.com.br", como_conheceu: "INDICAÇÃO DE UM PROFISSONAL")
DAIANEARAUJO = Cliente.create(nome: "DAIANE ARAUJO", telefone: "41 77 913 41 63", email: "araujo.paolieri@gmail.com", como_conheceu: "ANDRE AIMEC")
DANIELA1 = Cliente.create(nome: "DANIELA", telefone: "19 99152-3937", email: "WTZP", como_conheceu: "Não informado")
DANIELA2 = Cliente.create(nome: "DANIELA", telefone: "993474745", email: "dani.mq21@hotmail.com", como_conheceu: "INTERNET")
DANIELLIARAUJOCOSTA = Cliente.create(nome: "DANIELLI ARAUJO COSTA", telefone: "98898-2814", email: "danielli.araujocosta@hotmail.com", como_conheceu: "Não informado")
DANIELLIRAMOSTONHAI = Cliente.create(nome: "DANIELLI RAMOS TONHAI", telefone: "981638599", email: "danielletonhai@gmail.com", como_conheceu: "GOOGLE")
DEBORA = Cliente.create(nome: "DEBORA", telefone: "11996971757", email: "debora.passerine@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
DERIO = Cliente.create(nome: "DERIO", telefone: "989442361", email: "WTZP", como_conheceu: "NUCLEAR")
DJKUKAVICENTIN = Cliente.create(nome: "DJ KUKA VICENTIN", telefone: "11976688722", email: "kucavicentini@hotmail.com", como_conheceu: "VIA ANDRE CURADO")
ELAINE = Cliente.create(nome: "ELAINE    ", telefone: "98841-4865", email: "", como_conheceu: "DINA LELLIT")
ELIZABETHNEGRAES = Cliente.create(nome: "ELIZABETH NEGRAES", telefone: "1137985432", email: "elizabeth.negraes@hotmail.com", como_conheceu: "INTERNET")
ELLEN = Cliente.create(nome: "ELLEN", telefone: "11 95372-0659", email: "ellendalete@hotmail.com", como_conheceu: "INSTAGRAM")
ERICDEMOURABRAMBILA = Cliente.create(nome: "ERIC DE MOURA BRAMBILA", telefone: "996341820", email: "contatoericmoura@gmail.com", como_conheceu: "INTERNET")
ERIKAKAMPOS = Cliente.create(nome: "ERIKA KAMPOS", telefone: "99214-5406", email: "erika.campos92@yahoo.com.br", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
FABRINARIBEIRO = Cliente.create(nome: "FABRINA RIBEIRO", telefone: "989685953", email: "fabrina.ribeiro22@gmail.com", como_conheceu: "ANUNCIO NA INTERNET")
FELIPEMOREIRA = Cliente.create(nome: "FELIPE MOREIRA", telefone: "987712506", email: "feliper.moreira@hotmail.com", como_conheceu: "INTERNET")
FERNANDA1 = Cliente.create(nome: "FERNANDA", telefone: "993825119", email: "fernandassoave@gmail.com", como_conheceu: "INTERNET")
FERNANDA2 = Cliente.create(nome: "FERNANDA", telefone: "992424692", email: "fer-ps@hotmail.com", como_conheceu: "REDE SOCIAL")
FERNANDOASSISePATRICIA = Cliente.create(nome: "FERNANDO ASSIS e PATRICIA", telefone: "997190847", email: "nando_assis87@yahoo.com.br", como_conheceu: "GOOGLE")
FERNANDOECAROL = Cliente.create(nome: "FERNANDO E CAROL", telefone: "98293-9262", email: "fernando.s.f.garcia@hotmail.com", como_conheceu: "VIA ANDRE CURADO")
FLAVIACANTUSIOALINEELUCAS = Cliente.create(nome: "FLAVIA CANTUSIO - ALINE E LUCAS", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIOBEATRIZEFABRICIO = Cliente.create(nome: "FLAVIA CANTUSIO - BEATRIZ E FABRICIO", telefone: "32520975 - 11 982183524", email: "flavia@flaviacantusio.com.br, biafgomes@hotmail.com", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIOERIKAEMAURICIO = Cliente.create(nome: "FLAVIA CANTUSIO - ERIKA E MAURICIO", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIOGIOVANAEGUILHERME = Cliente.create(nome: "FLAVIA CANTUSIO - GIOVANA E GUILHERME", telefone: "99647-2147 ou 3252-0975 ", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIACANTUSIORAFAELAELUCAS = Cliente.create(nome: "FLAVIA CANTUSIO - RAFAELA E LUCAS", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "Não informado")
FLAVIACANTUSIOSTEPHANIEEEDUARDO = Cliente.create(nome: "FLAVIA CANTUSIO - STEPHANIE E EDUARDO", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "FLAVIA CANTUSIO")
FLAVIADIAS = Cliente.create(nome: "FLAVIA DIAS", telefone: "NÃO DEIXOU", email: "flavia.hdias@hotmail.com", como_conheceu: "ANGELINOS")
FLAVIAERICAEMAURICIO = Cliente.create(nome: "FLAVIA - ERICA E MAURICIO", telefone: "981861265", email: "flavia@flaviacantusio.com.br", como_conheceu: "Não informado")
FLAVIOCRUZ = Cliente.create(nome: "FLAVIO CRUZ", telefone: "11950790104", email: "flaviomfcruz@gmail.com", como_conheceu: "INTERNET")
GABRIELA = Cliente.create(nome: "GABRIELA", telefone: "992269996", email: "casamentobruwgabi@gmail.com", como_conheceu: "SITE DJ SONORIZACAO")
GABRIELAERODRIGO = Cliente.create(nome: "GABRIELA E RODRIGO", telefone: "99917-4400", email: "gabrielareginato87@gmail.com, rsruschel@gmail.com", como_conheceu: "RITA PONTES")
GABRIELASANTANA = Cliente.create(nome: "GABRIELA SANTANA", telefone: "992269996", email: "gabriella.satt@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
GLAUCIAERENAN = Cliente.create(nome: "GLAUCIA E RENAN", telefone: "98262-1391", email: "glau.lira16@hotmail.com, renann_sousa@hotmail.com", como_conheceu: "Não informado")
HEBERFOTOSGABRIEL = Cliente.create(nome: "HEBER FOTOS (GABRIEL)", telefone: "38621004 ou 999141393", email: "hebereventos@gmail.com", como_conheceu: "Não informado")
HELENAGUERRA = Cliente.create(nome: "HELENA GUERRA ", telefone: "99663-6315                        ", email: "", como_conheceu: "DINA LELLIT")
ISABELACAUMEPAULO = Cliente.create(nome: "ISABELA CAUM E PAULO", telefone: "99832-4590", email: "isabelacristinacaum@hotmail.com", como_conheceu: "INTERNET")
JACKFOCUSPRODUCOES = Cliente.create(nome: "JACK - FOCUS PRODUÇÕES", telefone: "-", email: "comercial@focusproducoes.com.br", como_conheceu: "Não informado")
JAQUELINE = Cliente.create(nome: "JAQUELINE", telefone: "-", email: "-", como_conheceu: "CASAMENTOS.COM.BR")
JAQUELINERAPHAELZOTARELI = Cliente.create(nome: "JAQUELINE (RAPHAEL ZOTARELI)", telefone: "99931-7179", email: "rafael.zotarelli@gmail.com", como_conheceu: "BUFFET SANTA MARIA")
JESSICA1 = Cliente.create(nome: "JESSICA", telefone: "988181132", email: "jessica.marquesani@gmail.com", como_conheceu: "GOOGLE")
JESSICA2 = Cliente.create(nome: "JESSICA", telefone: "99279-5930", email: "casamento2018.jehlucca@gmail.com", como_conheceu: "CASAMENTOS.COM.BR")
JESSICAGEREMIAS = Cliente.create(nome: "JESSICA  GEREMIAS                        ", telefone: "971529265", email: "", como_conheceu: "DINA LELLIT")
JOYCESANTOPEDRO = Cliente.create(nome: "JOYCE SANTO PEDRO", telefone: "999464844", email: "joyce-s-pedro@hotmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
JULIA = Cliente.create(nome: "JULIA", telefone: "11 99751-6333", email: "WHATS", como_conheceu: "MEDISONS")
JULIADEOLIVEIRA = Cliente.create(nome: "JULIA DE OLIVEIRA", telefone: "11975789487", email: "oliveira.oliveira51@hotmail.com.br", como_conheceu: "INTERNET")
JULIAISABELCURY = Cliente.create(nome: "JULIA - ISABEL CURY", telefone: "36336127", email: "julia.isabelcury@gmail.com", como_conheceu: "ISABEL CURY")
JULIANACAMPOS = Cliente.create(nome: "JULIANA CAMPOS", telefone: "991919431", email: "gcampos.juliana@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
JULIANACESARGRANJA = Cliente.create(nome: "JULIANA CESAR GRANJA", telefone: "11 991484367", email: "jucesargranja@gmail.com", como_conheceu: "INSTAGRAN")
JULIANAEEVERSON = Cliente.create(nome: "JULIANA E EVERSON", telefone: "JULIANA - 99721-2877           EVERSON - 99692-4988", email: "palaro.juliana@gmail.com", como_conheceu: "MOSTRA TH HADI")
JULIANAGURIAN = Cliente.create(nome: "JULIANA GURIAN", telefone: "99120-6849", email: "jugurian@hotmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
JULIOOHIRA = Cliente.create(nome: "JULIO OHIRA", telefone: "991143535", email: "julioc.ohira@outlook.com.br", como_conheceu: "INTERNET")
KARENEDANILO = Cliente.create(nome: "KAREN E DANILO", telefone: "991496673", email: "karenpg6@hotmail.com", como_conheceu: "FACEBOOK")
KARINAFUNARI = Cliente.create(nome: "KARINA FUNARI", telefone: "3881-9286", email: "karinaafunari@eaton.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
KARINENICOLETI = Cliente.create(nome: "KARINE NICOLETI", telefone: "97377-7863", email: "karine_nicolety@hotmail.com", como_conheceu: "Não informado")
KELMA = Cliente.create(nome: "KELMA", telefone: "32728683", email: "kelmabalista@hotmail.com", como_conheceu: "INTERNET")
KENNIASILVA = Cliente.create(nome: "KENNIA SILVA", telefone: "19998427584", email: "fskennia@gmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
LAIS = Cliente.create(nome: "LAIS", telefone: "991966977", email: "gabi.lais@hotmail.com", como_conheceu: "INTERNET")
LARISSAEVINICIUS = Cliente.create(nome: "LARISSA E VINICIUS  ", telefone: "-", email: "pavani_91@hotmail.com", como_conheceu: "RENATA 2M EVENTOS")
LARISSAHADASSAELUCIANO = Cliente.create(nome: "LARISSA - HADASSA E LUCIANO", telefone: "991823236", email: "contato@larissafarhat.comb.r", como_conheceu: "Não informado")
LEILAHPASSOS = Cliente.create(nome: "LEILAH PASSOS", telefone: "11 4237 2415", email: "leilah_passos@hotmail.com, julianalacerda@lufteventos.com.br, luftassessoria@gmail.com", como_conheceu: "INTERNET")
LETICIACRISTINACARAZATTOETHIAGOSOARESSILVA = Cliente.create(nome: "LETICIA CRISTINA CARAZATTO E THIAGO SOARES SILVA", telefone: "981405069", email: "leticiacarazzatto@hotmail.com, soaresthia@gmail.com", como_conheceu: "INTERNET")
LETICIAEJOAOPAULO = Cliente.create(nome: "LETICIA E JOAO PAULO", telefone: "LETICIA - 99353-7779                        JOAO PAULO - 99283-4904", email: "leticia.silva@hotmail.com", como_conheceu: "MOSTRA TH HADI")
LIA = Cliente.create(nome: "LIA", telefone: "33657280", email: "lia.wil@terra.com.br", como_conheceu: "GOOGLE")
LIDIANEBASCHIERA = Cliente.create(nome: "LIDIANE BASCHIERA", telefone: "98365-7575", email: "lidiane.arquitetura@hotmail.com", como_conheceu: "DINA LELLIT")
LIVIACASTRO = Cliente.create(nome: "LÍVIA CASTRO                        ", telefone: "991996558", email: "", como_conheceu: "DINA LELLIT")
LIVIADESOUZARODRIGUES = Cliente.create(nome: "LÍVIA DE SOUZA RODRIGUES             ", telefone: "982731384", email: "", como_conheceu: "DINA LELLIT")
LUCASEJULIANA = Cliente.create(nome: "LUCAS E JULIANA", telefone: "99155-5305", email: "luc.mendes13@gmail.com", como_conheceu: "MONTAGEM NO LOCAL")
LUCIANAROCHASOARES = Cliente.create(nome: "LUCIANA ROCHA SOARES", telefone: "998133298", email: "lulu.lrs@gmail.com", como_conheceu: "INTERNET")
LUCIMARPOSSARI = Cliente.create(nome: "LUCIMAR POSSARI", telefone: "98167-9480", email: "lucimar@lucimarpossari.com.br", como_conheceu: "LUCIMAR POSSARI")
MAISAMOREIRA = Cliente.create(nome: "MAÍSA MOREIRA", telefone: "98440-8764", email: "", como_conheceu: "DINA LELLIT")
MARCELA = Cliente.create(nome: "MARCELA", telefone: "19 99953-2227", email: "marcela.degrossoli@outlook.com ", como_conheceu: "Não informado")
MARCELOAMARAL = Cliente.create(nome: "MARCELO AMARAL", telefone: "1195177-7542 OU 11 5694-4122", email: "marcelo.amaral1@bayer.com", como_conheceu: "Não informado")
MARGARETHBARROS = Cliente.create(nome: "MARGARETH BARROS", telefone: "99615-2228", email: "margarethbarros@terra.com.br, contato@margarethbarros.com.br", como_conheceu: "MARGARETH BARROS")
MARIANA = Cliente.create(nome: "MARIANA", telefone: "991131067", email: "marianamoreiravet@hotmail.com", como_conheceu: "INDICAÇÃO DE CLIENTE")
MARIANAJACOBERENATO = Cliente.create(nome: "MARIANA JACOB  E RENATO", telefone: "998128188", email: "mariana.romanello@gmail.com, rseiti@gmail.com", como_conheceu: "RACHEL MIELLE")
MARIAVITORIA = Cliente.create(nome: "MARIA VITORIA", telefone: "997879373", email: "mavi.leao@gmail.com", como_conheceu: "INTERNET")
MARINAEANDRE = Cliente.create(nome: "MARINA E ANDRE", telefone: "11 98221 2336, 11 97336 0905", email: "marinaeandre2018@gmail.com", como_conheceu: "Não informado")
MAYRABONIN = Cliente.create(nome: "MAYRA BONIN", telefone: "99783-1718", email: "WHATS", como_conheceu: "LAURA SAVITCI")
MILENACAMPOS = Cliente.create(nome: "MILENA CAMPOS", telefone: "993324111", email: "", como_conheceu: "DINA LELLIT")
NADIAEGUSTAVO = Cliente.create(nome: "NADIA E GUSTAVO", telefone: "974074917", email: "nadiaferreira.almeida@gmail.com, gustavo8alvarenga@gmail.com", como_conheceu: "PAR PERFEITO")
NATALIA = Cliente.create(nome: "NATALIA", telefone: "98720-0072", email: "Natalia-sbm@outlook.com", como_conheceu: "INTERNET")
NATALIAEGUILHERME = Cliente.create(nome: "NATALIA E GUILHERME", telefone: "98128-1365 OU 992738004", email: "nanascferraz@gmail.com", como_conheceu: "THIAGO HADI")
NATALIAPOLONICORREA = Cliente.create(nome: "NATALIA POLÔNI CORRÊA", telefone: "984009546", email: "", como_conheceu: "DINA LELLIT")
NATALIEBRUNO = Cliente.create(nome: "NÁTALI E BRUNO", telefone: "11 97101 1992", email: "natali.romano@gmail.com", como_conheceu: "Não informado")
NATHALIASUNIGAEFERNANDO = Cliente.create(nome: "NATHALIA SUNIGA E FERNANDO", telefone: "999224343", email: "nathaliasuniga@cvc.com.br, nathi.fer.2018@gmail.com", como_conheceu: "SITE DECORAÇÃO")
NAYARAMACANOSSO = Cliente.create(nome: "NAYARA MACANOSSO                         ", telefone: "988670107", email: "", como_conheceu: "DINA LELLIT")
NEMELLYERAFAEL = Cliente.create(nome: "NEMELLY E RAFAEL", telefone: "994925000", email: "WHATS", como_conheceu: "GOOGLE")
NICOLEKARINAAMAE = Cliente.create(nome: "NICOLE (KARINA A MAE)", telefone: "988373030 OU 987313030 ", email: "WHATS", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
PALOMAERODRIGOCARLAROSSINI = Cliente.create(nome: "PALOMA E RODRIGO (CARLA ROSSINI)", telefone: "11 99215-5341", email: "carla@carlarossini.com.br", como_conheceu: "CARLA ROSSINI EDILAYNE FERRAZ")
PATRICIA = Cliente.create(nome: "PATRICIA", telefone: "982257112", email: "patriciaevesoares@gmail.com", como_conheceu: "INSTAGRAM")
PATRICIATENORIO = Cliente.create(nome: "PATRICIA TENORIO", telefone: "997945658", email: "drapatriciatenorio@bol.com.br", como_conheceu: "DINA LELLIT")
PAULA = Cliente.create(nome: "PAULA", telefone: "98127-2229", email: "  ", como_conheceu: "Não informado")
PAULOHENRIQUEDASILVA = Cliente.create(nome: "PAULO HENRIQUE DA SILVA", telefone: "998281804", email: "paulo_henriquesolva@yahoo.com.br", como_conheceu: "YOUTUBE")
PAULORBERNARDES = Cliente.create(nome: "PAULO R BERNARDES", telefone: "9 9626-3341", email: "bernardes.paulor@gmail.com", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
PRISCILA = Cliente.create(nome: "PRISCILA", telefone: "19 99112-7878", email: "priscilataveira@yahoo.com.br", como_conheceu: "KRATOS")
PRISCILAEJOAO = Cliente.create(nome: "PRISCILA E JOÃO", telefone: "99448-7357", email: "pri.dalmolin.carvalho@gmail.com", como_conheceu: "CRIS BLESS")
RAPHAELALVEZ = Cliente.create(nome: "RAPHAEL ALVEZ", telefone: "98321-7473", email: "rafaelalvescerimonial@gmail.com", como_conheceu: "RAFAEL ALVES")
RAQUELEGUILHERME = Cliente.create(nome: "RAQUEL E GUILHERME", telefone: "995920592", email: "raquel@smass.com.br", como_conheceu: "Não informado")
REBECAEFELIPE = Cliente.create(nome: "REBECA E FELIPE  ", telefone: "-", email: "rebeca.s.venturini@gmail.com", como_conheceu: "RENATA 2M EVENTOS")
RENATA2MEVENTOSHELOISAEFELIPE = Cliente.create(nome: "RENATA 2M EVENTOS - HELOISA E FELIPE", telefone: "996825662", email: "helo_poltronieri@hotmail.com, renata@doismeventos.com.br", como_conheceu: "2M EVENTOS")
RENATASARITAEEDUARDO = Cliente.create(nome: "RENATA - SARITA E EDUARDO ", telefone: "99682-5662", email: "saritaeeduardo@gmail.com, renata@doismeventos.com.br", como_conheceu: "RENATA 2M EVENTOS")
RICARDODOPRADOLAIA = Cliente.create(nome: "RICARDO DO PRADO LAIA", telefone: "998348461", email: "prado.r10@gmail.com", como_conheceu: "INTERNET")
RICARDOEJULIANA = Cliente.create(nome: "RICARDO E JULIANA", telefone: "99786-9787", email: "frealdoricardo@hotmail.com", como_conheceu: "DEGUSTAÇÃO ANGELINOS")
RITAEGERALDO = Cliente.create(nome: "RITA E GERALDO", telefone: "988600624", email: "barbarasousalopes@hotmail.com", como_conheceu: "Não informado")
ROBERTAEKAIO = Cliente.create(nome: "ROBERTA E KAIO  ", telefone: "-", email: "ro.raphaelli@gmail.com", como_conheceu: "RENATA 2M EVENTOS")
ROBERTFELDER = Cliente.create(nome: "ROBERT FELDER", telefone: "11 983678490", email: "felder_robert@hotmail.com", como_conheceu: "Não informado")
ROSANALEITE = Cliente.create(nome: "ROSANA LEITE", telefone: "982445440", email: "rosana.leita@hotmail.com", como_conheceu: "INSTAGRAM")
SALETEMICHELEEFLAVIO = Cliente.create(nome: "SALETE - MICHELE E FLAVIO", telefone: "974043043", email: "contato@saletecoelho.com.br", como_conheceu: "INTERNET")
SILVIA = Cliente.create(nome: "SILVIA", telefone: "11975958555", email: "silvia@airtraining.com.br", como_conheceu: "REVISTA")
SONIA = Cliente.create(nome: "SONIA", telefone: "991115808", email: "sonialevantezi@gmail.com", como_conheceu: "SUIT FILMES")
SULAMITAFERREIRAPICCOLIeMATHEUS = Cliente.create(nome: "SULAMITA FERREIRA PICCOLI e MATHEUS", telefone: "998514222 ou 98298-9957", email: "sulamitafp@hotmail.com", como_conheceu: "CASAMENTOS.COM.BR")
TALITAECLEVERTON = Cliente.create(nome: "TALITA E CLEVERTON", telefone: "99221-1183", email: "", como_conheceu: "INDICAÇÃO DE UM PROFISSIONAL")
TANIAMARIAFORTUNATO = Cliente.create(nome: "TÂNIA MARIA FORTUNATO", telefone: "981572646", email: "", como_conheceu: "DINA LELLIT")
TATIANA = Cliente.create(nome: "TATIANA", telefone: "19 99633-1355", email: "tatiflauzino@gmail.com", como_conheceu: "Não informado")
TAYNA = Cliente.create(nome: "TAYNÁ", telefone: "992255388", email: "tayna.santtos1@outlook.com", como_conheceu: "INTERNET")
THAINAEHEINRIQUE = Cliente.create(nome: "THAINA E HEINRIQUE", telefone: "99752-6051", email: "thaaipinheiro@hotmail.com", como_conheceu: "2M EVENTOS")
THAINAEHENRIQUE = Cliente.create(nome: "THAINA E HENRIQUE ", telefone: "-", email: "thaaipinheiro@hotmail.com", como_conheceu: "RENATA 2M EVENTOS")
THAISCAROLINEERENAN = Cliente.create(nome: "THAIS CAROLINE  E RENAN", telefone: "993912292", email: "taiserenan@yahoo.com, taiserenan@yahoo.com.br, tcfeichas@hotmail.com", como_conheceu: "DINA LELLIT")
THAISEPEDRO = Cliente.create(nome: "THAIS E PEDRO  ", telefone: "-", email: "td.pina@bol.com.br", como_conheceu: "RENATA 2M EVENTOS")
THAISPAOLA = Cliente.create(nome: "THAIS PAOLA", telefone: "993762128, 99376212", email: "thais.corsatto@hotmail.com", como_conheceu: "ANUNCIO NA INTERNET")
THATIANEFANTINI = Cliente.create(nome: "THATIANE FANTINI", telefone: "983583059", email: "contato@fantini.adv.br", como_conheceu: "ANUNCIO NA INTERNET")
THAYNARA = Cliente.create(nome: "THAYNARA ", telefone: "99894-4609", email: "", como_conheceu: "DINA LELLIT")
THIAGOARTMIDIA = Cliente.create(nome: "THIAGO ART MIDIA", telefone: "WTZP", email: "-", como_conheceu: "Não informado")
TULIO = Cliente.create(nome: "TULIO", telefone: "97155-0123", email: "tulio_manzano@hotmail.com", como_conheceu: "INDICAÇÇÃO DE UM PROFISSIONAL")
VALDICEABREU = Cliente.create(nome: "VALDICE ABREU", telefone: "11 99243-3926", email: "val.amelia@valamelia.com.br", como_conheceu: "VALDICE ABREU")
VANESSAFACCHIN = Cliente.create(nome: "VANESSA FACCHIN", telefone: "993589970", email: "vanessa.facchin@hotmail.com", como_conheceu: "INTERNET")
VANESSARODRIGUES = Cliente.create(nome: "VANESSA RODRIGUES", telefone: "996654506", email: "vancrodrigues@hotmail.com", como_conheceu: "INTERNET")
VERONICA = Cliente.create(nome: "VERONICA", telefone: "19996282603", email: "", como_conheceu: "DINA LELLIT")
VILMAEARLINDOMANOELA = Cliente.create(nome: "VILMA E ARLINDO - MANOELA", telefone: "988611690", email: "vilma@aevseguros.com.br", como_conheceu: "EDILAYNE FERRAZ")
VINICIUSDAFINE = Cliente.create(nome: "VINICIUS - DAFINE", telefone: "WHATS", email: "vinicius@lucimarpossari.com.br", como_conheceu: "LUCIMAR POSSARI")
VIRGINIALABARCA = Cliente.create(nome: "VIRGINIA LABARCA", telefone: "983829209", email: "vilabarca@gmail.com", como_conheceu: "PUBLICIDADE")
VIVIANCAMILAEMURILO = Cliente.create(nome: "VIVIAN - CAMILA E MURILO", telefone: "98177-4437", email: "vivian@vivianbatiston.com.br", como_conheceu: "PELO CLIENTE DA FAZENDA TRES AUGUSTUS")
VIVIANE = Cliente.create(nome: "VIVIANE", telefone: "13 988420299", email: "viviane.goncalves@msn.com ", como_conheceu: "YOUTUBE")
VIVIANMOTAJULIAEDANIEL = Cliente.create(nome: "VIVIAN MOTA - JULIA E DANIEL", telefone: "981833818", email: "WTZP", como_conheceu: "INDICAÇÃO DE CLIENTE")


###########################################################################################################################
######################################################### LOCAIS ##########################################################
###########################################################################################################################
ITAPIRA = Local.create(nome: "ITAPIRA", endereco: "ITAPIRA", cidade: "Campinas", estado: "SP")
ROYALCLINETEFOCUSPRODUCOES = Local.create(nome: "ROYAL - CLINETE FOCUS PRODUÇÕES", endereco: "ROYAL - CLINETE FOCUS PRODUÇÕES", cidade: "Campinas", estado: "SP")
REDEVENTOSJAGUARIUNA = Local.create(nome: "RED EVENTOS - JAGUARIUNA", endereco: "RED EVENTOS - JAGUARIUNA", cidade: "Campinas", estado: "SP")
LAGOASANTARITA = Local.create(nome: "LAGOA SANTA RITA", endereco: "LAGOA SANTA RITA", cidade: "Campinas", estado: "SP")
ESPACODONAINES = Local.create(nome: "ESPAÇO DONA INES", endereco: "ESPAÇO DONA INES", cidade: "Campinas", estado: "SP")
HOTELPLAZA = Local.create(nome: "HOTEL PLAZA", endereco: "HOTEL PLAZA", cidade: "Campinas", estado: "SP")
CHATEAUDUSOLANOS = Local.create(nome: "CHATEAU DU SOLANOS", endereco: "CHATEAU DU SOLANOS", cidade: "Campinas", estado: "SP")
VILLAFLOR = Local.create(nome: "VILLA FLOR", endereco: "VILLA FLOR", cidade: "Campinas", estado: "SP")
LEBLANC = Local.create(nome: "LE BLANC", endereco: "LE BLANC", cidade: "Campinas", estado: "SP")
BOSCH = Local.create(nome: "BOSCH", endereco: "BOSCH", cidade: "Campinas", estado: "SP")
PORTALGIRASSOL = Local.create(nome: "PORTAL GIRASSOL", endereco: "PORTAL GIRASSOL", cidade: "Campinas", estado: "SP")
SOUZAS = Local.create(nome: "SOUZAS", endereco: "Av. Dona Julia da Conceição Alves, 608 Sousas ", cidade: "Campinas", estado: "SP")
CAMPINAS = Local.create(nome: "CAMPINAS", endereco: "CAMPINAS", cidade: "Campinas", estado: "SP")
FLORDELOTUS = Local.create(nome: "FLOR DE LOTUS", endereco: "FLOR DE LOTUS", cidade: "Campinas", estado: "SP")
ANGELINOS = Local.create(nome: "ANGELINOS", endereco: "ANGELINOS", cidade: "Campinas", estado: "SP")
HIPNOSE = Local.create(nome: "HIPNOSE", endereco: "HIPNOSE", cidade: "Campinas", estado: "SP")
ESPACOM_DIMOND = Local.create(nome: "ESPAÇO M (DIMOND)", endereco: "JUNDIAI - ESPAÇO M (DIMOND)", cidade: "Campinas", estado: "SP")
CHACARAPARAISO = Local.create(nome: "CHACARA PARAISO", endereco: "CHACARA PARAISO", cidade: "Campinas", estado: "SP")
ESPACOBARAO = Local.create(nome: "ESPAÇO BARAO", endereco: "ESPAÇO BARAO", cidade: "Campinas", estado: "SP")
swisspark = Local.create(nome: "swiss park", endereco: "swiss park", cidade: "Campinas", estado: "SP")
ALPHAVILLE = Local.create(nome: "ALPHAVILLE", endereco: "ALPHAVILLE", cidade: "Campinas", estado: "SP")
SALAOCONDOMINIO = Local.create(nome: "SALAO CONDOMINIO", endereco: "JUNDIAI - SALAO CONDOMINIO", cidade: "Campinas", estado: "SP")
POTPOURRITCLASSICO = Local.create(nome: "POT POURRIT CLASSICO", endereco: "POT POURRIT CLASSICO", cidade: "Campinas", estado: "SP")
QUINTADASBROMELIAS = Local.create(nome: "QUINTA DAS BROMELIAS", endereco: "QUINTA DAS BROMELIAS", cidade: "Campinas", estado: "SP")
BUFFETIMAGEMCAMPESTRE = Local.create(nome: "BUFFET IMAGEM CAMPESTRE", endereco: "BUFFET IMAGEM CAMPESTRE", cidade: "Campinas", estado: "SP")
SPAZIOTRAMONTI = Local.create(nome: "SPAZIO TRAMONTI", endereco: "SPAZIO TRAMONTI", cidade: "Campinas", estado: "SP")
ESPACOCAMBARA = Local.create(nome: "ESPAÇO CAMBARÁ", endereco: "ESPAÇO CAMBARÁ", cidade: "Campinas", estado: "SP")
SHOPINGGALERIA = Local.create(nome: "SHOPING GALERIA", endereco: "SHOPING GALERIA", cidade: "Campinas", estado: "SP")
DUASMARIAS = Local.create(nome: "DUAS MARIAS", endereco: "DUAS MARIAS", cidade: "Campinas", estado: "SP")
ESPACOSUPREMO = Local.create(nome: "ESPAÇO SUPREMO", endereco: "ESPAÇO SUPREMO", cidade: "Campinas", estado: "SP")
IDEIAS3 = Local.create(nome: "3 IDEIAS", endereco: "3 IDEIAS", cidade: "Campinas", estado: "SP")
FLORESTAPARKCAMPINAS = Local.create(nome: "FLORESTA PARK CAMPINAS", endereco: "FLORESTA PARK CAMPINAS", cidade: "Campinas", estado: "SP")
ESPACOHIBISCUSPAULINIA = Local.create(nome: "ESPAÇO HIBISCUS PAULÍNIA", endereco: "ESPAÇO HIBISCUS PAULÍNIA", cidade: "Campinas", estado: "SP")
SERRANEGRADONAELZA = Local.create(nome: "SERRA NEGRA DONA ELZA", endereco: "SERRA NEGRA DONA ELZA", cidade: "Campinas", estado: "SP")
ESPACOSONHOREALIZADO = Local.create(nome: "ESPAÇO SONHO REALIZADO", endereco: "MONTE MOR - ESPAÇO SONHO REALIZADO", cidade: "Campinas", estado: "SP")
LANUIT = Local.create(nome: "LA NUIT", endereco: "LA NUIT", cidade: "Campinas", estado: "SP")
CULTURADECAMPO = Local.create(nome: "CULTURA DE CAMPO", endereco: "CULTURA DE CAMPO", cidade: "Campinas", estado: "SP")
VIAAPPIA = Local.create(nome: "VIA APPIA", endereco: "VIA APPIA", cidade: "Campinas", estado: "SP")
BUFFETIMAGEMCONTEMPORANEO = Local.create(nome: "BUFFET IMAGEM CONTEMPORANEO", endereco: "BUFFET IMAGEM CONTEMPORANEO", cidade: "Campinas", estado: "SP")
ANGELINOSOUMONETEVENTOS = Local.create(nome: "ANGELINOS OU MONET EVENTOS", endereco: "ANGELINOS OU MONET EVENTOS", cidade: "Campinas", estado: "SP")
VALEDOSSONHOS = Local.create(nome: "VALE DOS SONHOS", endereco: "VALE DOS SONHOS", cidade: "Campinas", estado: "SP")
VILADELIKATESSEN = Local.create(nome: "VILA DELIKATESSEN", endereco: "VILA DELIKATESSEN", cidade: "Campinas", estado: "SP")
ITATIBASERRADOSCOCAIS = Local.create(nome: "ITATIBA SERRA DOS COCAIS", endereco: "ITATIBA SERRA DOS COCAIS", cidade: "Campinas", estado: "SP")
JACUTINGA = Local.create(nome: "JACUTINGA", endereco: "JACUTINGA", cidade: "Campinas", estado: "SP")
PAULINIAHIBISCUS = Local.create(nome: "PAULINIA HIBISCUS", endereco: "PAULINIA HIBISCUS", cidade: "Campinas", estado: "SP")
FAZENDADASCABRAS = Local.create(nome: "FAZENDA DAS CABRAS", endereco: "FAZENDA DAS CABRAS", cidade: "Campinas", estado: "SP")
FLORIADAEVENTOS = Local.create(nome: "FLORIADA EVENTOS", endereco: "FLORIADA EVENTOS", cidade: "Campinas", estado: "SP")
BELMONTEEVENTOS = Local.create(nome: "BELMONTE EVENTOS", endereco: "BELMONTE EVENTOS", cidade: "Campinas", estado: "SP")
ESPACOFOLHAEAGUA = Local.create(nome: "ESPAÇO FOLHA E AGUA", endereco: "ESPAÇO FOLHA E AGUA", cidade: "Campinas", estado: "SP")
VILASANSU = Local.create(nome: "VILA SANSU", endereco: "VILA SANSU", cidade: "Campinas", estado: "SP")
ALTODASPALMEIRAS = Local.create(nome: "ALTO DAS PALMEIRAS", endereco: "ALTO DAS PALMEIRAS", cidade: "Campinas", estado: "SP")
BUFFETEVENTUSPIRACICABA = Local.create(nome: "BUFFET EVENTUS - PIRACICABA", endereco: "BUFFET EVENTUS - PIRACICABA", cidade: "Campinas", estado: "SP")
ESPACODOISIRMAOS = Local.create(nome: "ESPAÇO DOIS IRMAOS", endereco: "ESPAÇO DOIS IRMAOS", cidade: "Campinas", estado: "SP")
BUFFETIMAGEM = Local.create(nome: "BUFFET IMAGEM", endereco: "BUFFET IMAGEM", cidade: "Campinas", estado: "SP")
VALINHOS = Local.create(nome: "VALINHOS", endereco: "VALINHOS", cidade: "Campinas", estado: "SP")
KRATOS = Local.create(nome: "KRATOS", endereco: "KRATOS", cidade: "Campinas", estado: "SP")
TENISCLUBE = Local.create(nome: "TENIS CLUBE", endereco: "TENIS CLUBE", cidade: "Campinas", estado: "SP")
MONTECASTELO = Local.create(nome: "MONTE CASTELO", endereco: "MONTE CASTELO", cidade: "Campinas", estado: "SP")
ESPACOTERRAZZA = Local.create(nome: "ESPAÇO TERRAZZA", endereco: "ESPAÇO TERRAZZA", cidade: "Campinas", estado: "SP")
VILAMANRESA = Local.create(nome: "VILA MANRESA", endereco: "VILA MANRESA", cidade: "Campinas", estado: "SP")
ESPACOBELAVISTA = Local.create(nome: "ESPAÇO BELA VISTA", endereco: "ESPAÇO BELA VISTA", cidade: "Campinas", estado: "SP")
ESPACOMEDIEVALCASTELODOSVINHAIS = Local.create(nome: "ESPAÇO MEDIEVAL - CASTELO DOS VINHAIS", endereco: "ESPAÇO MEDIEVAL - CASTELO DOS VINHAIS", cidade: "Campinas", estado: "SP")
ESPACOSANTAESPLENDORROOM = Local.create(nome: "ESPAÇO SANTA ESPLENDOR ROOM", endereco: "ESPAÇO SANTA ESPLENDOR ROOM", cidade: "Campinas", estado: "SP")
HELENOFESTAS = Local.create(nome: "HELENO FESTAS", endereco: "HELENO FESTAS", cidade: "Campinas", estado: "SP")
CASAPALMEIRA = Local.create(nome: "CASA PALMEIRA", endereco: "CASA PALMEIRA", cidade: "Campinas", estado: "SP")
RANCHOAVEIRO = Local.create(nome: "RANCHO AVEIRO", endereco: "RANCHO AVEIRO", cidade: "Campinas", estado: "SP")
ESPACOVILAVERDE = Local.create(nome: "ESPAÇO VILA VERDE", endereco: "ESPAÇO VILA VERDE", cidade: "Campinas", estado: "SP")
PEDREIRAQUINTADOLAGO = Local.create(nome: "PEDREIRA - QUINTA DO LAGO", endereco: "PEDREIRA - QUINTA DO LAGO", cidade: "Campinas", estado: "SP")
GUANABARA = Local.create(nome: "GUANABARA", endereco: "GUANABARA", cidade: "Campinas", estado: "SP")
THEROYALIMPERIAL = Local.create(nome: "THE ROYAL  - IMPERIAL", endereco: "THE ROYAL  - IMPERIAL", cidade: "Campinas", estado: "SP")
FAZENDALAGEADO = Local.create(nome: "FAZENDA LAGEADO", endereco: "FAZENDA LAGEADO", cidade: "Campinas", estado: "SP")
BUFFETIMAGEMMEDIEVAL = Local.create(nome: "BUFFET IMAGEM MEDIEVAL", endereco: "BUFFET IMAGEM MEDIEVAL", cidade: "Campinas", estado: "SP")
BOATEHIPICA = Local.create(nome: "BOATE HIPICA", endereco: "BOATE HIPICA", cidade: "Campinas", estado: "SP")
ESPACO55 = Local.create(nome: "ESPAÇO 55", endereco: "INDAIATUBA - ESPAÇO 55", cidade: "Campinas", estado: "SP")
VILLAHARMONIA = Local.create(nome: "VILLA HARMONIA", endereco: "VILLA HARMONIA", cidade: "Campinas", estado: "SP")
CHACARARECANTODOSPASSAROS = Local.create(nome: "CHACARA RECANTO DOS PASSAROS", endereco: "CHACARA RECANTO DOS PASSAROS", cidade: "Campinas", estado: "SP")
FONTESAOPAULO = Local.create(nome: "FONTE SÃO PAULO", endereco: "FONTE SÃO PAULO", cidade: "Campinas", estado: "SP")
HARASDAFAMILIA = Local.create(nome: "HARAS DA FAMILIA", endereco: "HARAS DA FAMILIA", cidade: "Campinas", estado: "SP")
LEPARTIE = Local.create(nome: "LE PARTIE", endereco: "LE PARTIE", cidade: "Campinas", estado: "SP")
THEROYAL = Local.create(nome: "THE ROYAL", endereco: "THE ROYAL", cidade: "Campinas", estado: "SP")
HIPICASOCIAL = Local.create(nome: "HIPICA SOCIAL", endereco: "HIPICA SOCIAL", cidade: "Campinas", estado: "SP")
BUFFETCLIMATROPICAL = Local.create(nome: "BUFFET CLIMA TROPICAL", endereco: "BUFFET CLIMA TROPICAL", cidade: "Campinas", estado: "SP")
VILASAOVITO = Local.create(nome: "VILA SÃO VITO", endereco: "VILA SÃO VITO", cidade: "Campinas", estado: "SP")
AGUASDELINDOIA = Local.create(nome: "AGUAS DE LINDOIA", endereco: "AGUAS DE LINDOIA", cidade: "Campinas", estado: "SP")
VERDANOEVENTOS = Local.create(nome: "VERDANO EVENTOS", endereco: "VERDANO EVENTOS", cidade: "Campinas", estado: "SP")
CAMBARAFESTAS = Local.create(nome: "CAMBARA FESTAS", endereco: "CAMBARA FESTAS", cidade: "Campinas", estado: "SP")
HOTELVITORIA = Local.create(nome: "HOTEL VITORIA", endereco: "HOTEL VITORIA", cidade: "Campinas", estado: "SP")
WETNWILD = Local.create(nome: "WETN WILD", endereco: "WETN WILD", cidade: "Campinas", estado: "SP")



###########################################################################################################################
######################################################### EVENTOS #########################################################
###########################################################################################################################
evento1  = Evento.create(cliente_id: DERIO.id, data_evento: '13-01-2018 00:00', tipo_evento_id:CORPORATIVO.id, evento_status:1, local_id: ITAPIRA.id)
evento2  = Evento.create(cliente_id: JACKFOCUSPRODUCOES.id, data_evento: '17-01-2018 00:00', tipo_evento_id:CORPORATIVO.id, evento_status:4, local_id: ROYALCLINETEFOCUSPRODUCOES.id)
evento3  = Evento.create(cliente_id: HEBERFOTOSGABRIEL.id, data_evento: '20-01-2018 22:00', tipo_evento_id:FORMATURA.id, evento_status:4, local_id: REDEVENTOSJAGUARIUNA.id, quantidade_horas: 6)
evento4  = Evento.create(cliente_id: ANNEELUCAS.id, data_evento: '20-01-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: LAGOASANTARITA.id)
evento5  = Evento.create(cliente_id: DJKUKAVICENTIN.id, data_evento: '27-01-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: ESPACODONAINES.id, quantidade_horas: 18)
evento6  = Evento.create(cliente_id: KARINAFUNARI.id, data_evento: '01-02-2018 00:00', tipo_evento_id:CORPORATIVO.id, evento_status:1, local_id: HOTELPLAZA.id)
evento7  = Evento.create(cliente_id: HELENAGUERRA.id, tipo_evento_id:CASAMENTO.id, evento_status:2)
evento8  = Evento.create(cliente_id: VIVIANCAMILAEMURILO.id, data_evento: '03-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CHATEAUDUSOLANOS.id)
evento9  = Evento.create(cliente_id: SONIA.id, data_evento: '03-02-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: VILLAFLOR.id)
evento10 = Evento.create(cliente_id: FLAVIACANTUSIOSTEPHANIEEEDUARDO.id, data_evento: '03-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LEBLANC.id)
evento11 = Evento.create(cliente_id: MARIAVITORIA.id, data_evento: '04-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BOSCH.id)
evento12 = Evento.create(cliente_id: FLAVIACANTUSIOALINEELUCAS.id, data_evento: '10-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PORTALGIRASSOL.id)
evento13 = Evento.create(cliente_id: CASSIATAYRINE.id, data_evento: '10-02-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: SOUZAS.id)
evento14 = Evento.create(cliente_id: FERNANDA1.id, data_evento: '12-02-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CAMPINAS.id)
evento15 = Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '23-02-2018 00:00', tipo_evento_id:FORMATURA.id, evento_status:1, local_id: FLORDELOTUS.id)
evento16 = Evento.create(cliente_id: FLAVIADIAS.id, data_evento: '06-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento17 = Evento.create(cliente_id: CARINAEANTONY.id, data_evento: '03-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:5, local_id: HIPNOSE.id)
evento18 = Evento.create(cliente_id: JULIADEOLIVEIRA.id, data_evento: '03-03-2018 00:00', tipo_evento_id:FORMATURA.id, evento_status:1, local_id: ESPACOM_DIMOND.id, observacao: 'INDICAÇÃO DE UMA NOIVAM QUE CASOU NO LOCAL')
evento19 = Evento.create(cliente_id: GABRIELA.id, data_evento: '09-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:1, local_id: ANGELINOS.id, observacao: 'THAISA AGUAS DE LINDOIA')
evento20 = Evento.create(cliente_id: SILVIA.id, data_evento: '09-03-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CHACARAPARAISO.id)
evento21 = Evento.create(cliente_id: DANIELA1.id, data_evento: '10-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:1, local_id: ESPACOBARAO.id)
evento22 = Evento.create(cliente_id: KENNIASILVA.id, data_evento: '10-03-2018 00:00', tipo_evento_id:CASAMENTO .id, evento_status:3, local_id: swisspark.id)
evento23 = Evento.create(cliente_id: RITAEGERALDO.id, data_evento: '16-03-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:5, local_id: ESPACOBARAO.id)
evento24 = Evento.create(cliente_id: CAROLINEBRITO.id, data_evento: '17-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento25 = Evento.create(cliente_id: FLAVIACANTUSIOBEATRIZEFABRICIO.id, data_evento: '17-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ALPHAVILLE.id)
evento26 = Evento.create(cliente_id: JULIA.id, data_evento: '02-02-2018 00:00', tipo_evento_id:ANIVERSARIO.id, evento_status:1, local_id: SALAOCONDOMINIO.id)
evento27 = Evento.create(cliente_id: LETICIACRISTINACARAZATTOETHIAGOSOARESSILVA.id, data_evento: '23-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: POTPOURRITCLASSICO.id)
evento28 = Evento.create(cliente_id: LUCIANAROCHASOARES.id, data_evento: '23-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
evento29 = Evento.create(cliente_id: FERNANDA2.id, data_evento: '24-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PORTALGIRASSOL.id)
evento30 = Evento.create(cliente_id: JULIANACAMPOS.id, data_evento: '24-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOBARAO.id)
evento31 = Evento.create(cliente_id: SULAMITAFERREIRAPICCOLIeMATHEUS.id, data_evento: '30-03-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id)
evento32 = Evento.create(cliente_id: VILMAEARLINDOMANOELA.id, data_evento: '06-04-2018 21:00', tipo_evento_id:DEBUTANTE.id, evento_status:4, local_id: BUFFETIMAGEMCAMPESTRE.id, quantidade_horas: 6)
evento33 = Evento.create(cliente_id: LEILAHPASSOS.id, data_evento: '07-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: SPAZIOTRAMONTI.id, quantidade_horas: 7)
evento34 = Evento.create(cliente_id: FLAVIACANTUSIOGIOVANAEGUILHERME.id, data_evento: '07-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ESPACOCAMBARA.id)
evento35 = Evento.create(cliente_id: THATIANEFANTINI.id, data_evento: '07-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: SHOPINGGALERIA.id)
evento36 = Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '08-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id, observacao: 'Noivos: MAINÁ E VINICIUS')
evento37 = Evento.create(cliente_id: RENATA2MEVENTOSHELOISAEFELIPE.id, data_evento: '14-04-2018 17:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: DUASMARIAS.id, quantidade_horas: 8)
evento38 = Evento.create(cliente_id: NADIAEGUSTAVO.id, data_evento: '14-04-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: ESPACOBARAO.id, quantidade_horas: 6,)
evento39 = Evento.create(cliente_id: MARIANAJACOBERENATO.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ESPACOSUPREMO.id)
evento40 = Evento.create(cliente_id: JULIAISABELCURY.id, data_evento: '14-04-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: IDEIAS3.id)
evento41 = Evento.create(cliente_id: FERNANDOECAROL.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORESTAPARKCAMPINAS.id)
evento42 = Evento.create(cliente_id: JOYCESANTOPEDRO.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
evento43 = Evento.create(cliente_id: CLELIAMDOPRADO.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOHIBISCUSPAULINIA.id)
evento44 = Evento.create(cliente_id: MARIANA.id, data_evento: '14-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: SERRANEGRADONAELZA.id)
evento45 = Evento.create(cliente_id: LETICIAEJOAOPAULO.id, data_evento: '21-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: BUFFETIMAGEMCAMPESTRE.id)
evento46 = Evento.create(cliente_id: CARLAANALUISA.id, data_evento: '21-04-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:5, local_id: ANGELINOS.id)
evento47 = Evento.create(cliente_id: DANIELLIARAUJOCOSTA.id, data_evento: '21-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSONHOREALIZADO.id)
evento48 = Evento.create(cliente_id: DANIELA2.id, data_evento: '21-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
evento49 = Evento.create(cliente_id: LIA.id, data_evento: '21-04-2018 00:00', tipo_evento_id:BODAS.id, evento_status:1, local_id: CULTURADECAMPO.id)
evento50 = Evento.create(cliente_id: CLAUDIATHIAGOHADI.id, data_evento: '27-04-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: VIAAPPIA.id)
evento51 = Evento.create(cliente_id: BRUNAMARCELAEDIEGO.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id)
evento52 = Evento.create(cliente_id: VIRGINIALABARCA.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORESTAPARKCAMPINAS.id)
evento53 = Evento.create(cliente_id: JESSICA1.id, data_evento: '29-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCONTEMPORANEO.id)
evento54 = Evento.create(cliente_id: RICARDOEJULIANA.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOSOUMONETEVENTOS.id)
evento55 = Evento.create(cliente_id: ALINE.id, data_evento: '28-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VALEDOSSONHOS.id)
evento56 = Evento.create(cliente_id: TULIO.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILADELIKATESSEN.id)
evento57 = Evento.create(cliente_id: VALDICEABREU.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ITATIBASERRADOSCOCAIS.id)
evento58 = Evento.create(cliente_id: THIAGOARTMIDIA.id, data_evento: '05-05-2018 00:00', tipo_evento_id:LOCACAO.id, evento_status:1, local_id: JACUTINGA.id)
evento59 = Evento.create(cliente_id: LAIS.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
evento60 = Evento.create(cliente_id: CAMILAEBRUNO.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PAULINIAHIBISCUS.id)
evento61 = Evento.create(cliente_id: ROBERTFELDER.id, data_evento: '05-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FAZENDADASCABRAS.id)
evento62 = Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '11-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id, observacao: 'Noivos: ISABELA E DANILO')
evento63 = Evento.create(cliente_id: THAINAEHEINRIQUE.id, data_evento: '19-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORIADAEVENTOS.id)
evento64 = Evento.create(cliente_id: LUCASEJULIANA.id, data_evento: '19-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BELMONTEEVENTOS.id)
evento65 = Evento.create(cliente_id: JULIANAEEVERSON.id, data_evento: '26-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
evento66 = Evento.create(cliente_id: NATALIAEGUILHERME.id, data_evento: '26-05-2018 19:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: ESPACOFOLHAEAGUA.id, quantidade_horas: 7)
evento67 = Evento.create(cliente_id: ANACAROLINA.id, data_evento: '27-05-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILASANSU.id)
evento68 = Evento.create(cliente_id: PRISCILAEJOAO.id, data_evento: '02-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: QUINTADASBROMELIAS.id)
evento69 = Evento.create(cliente_id: GABRIELAERODRIGO.id, data_evento: '08-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ALTODASPALMEIRAS.id, observacao: 'INDICACAO DE UM AMIGO QUE VAI FAZER A FESTA CONOSCO MARCINHO QUE TOCOU')
evento70 = Evento.create(cliente_id: FERNANDOASSISePATRICIA.id, data_evento: '09-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ITATIBASERRADOSCOCAIS.id)
evento71 = Evento.create(cliente_id: LUCIMARPOSSARI.id, data_evento: '09-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ITATIBASERRADOSCOCAIS.id)
evento72 = Evento.create(cliente_id: CAROLINAPASSARELLI.id, data_evento: '16-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETEVENTUSPIRACICABA.id)
evento73 = Evento.create(cliente_id: ROSANALEITE.id, data_evento: '16-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACODOISIRMAOS.id)
evento74 = Evento.create(cliente_id: PATRICIA.id, data_evento: '30-06-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSUPREMO.id)
evento75 = Evento.create(cliente_id: ANACLAUDIA.id, data_evento: '07-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEM.id)
evento76 = Evento.create(cliente_id: THAISPAOLA.id, data_evento: '07-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VALINHOS.id)
evento77 = Evento.create(cliente_id: AMANDADEPAOLA.id, data_evento: '07-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: KRATOS.id)
evento78 = Evento.create(cliente_id: GABRIELASANTANA.id, data_evento: '08-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
evento79 = Evento.create(cliente_id: FLAVIACANTUSIOERIKAEMAURICIO.id, data_evento: '13-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento80 = Evento.create(cliente_id: VIVIANMOTAJULIAEDANIEL.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: TENISCLUBE.id)
evento81 = Evento.create(cliente_id: MARCELOAMARAL.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LAGOASANTARITA.id)
evento82 = Evento.create(cliente_id: JULIANAGURIAN.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento83 = Evento.create(cliente_id: ERIKAKAMPOS.id, data_evento: '14-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento84 = Evento.create(cliente_id: ALEXANDREFORA.id, data_evento: '21-07-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:4)
evento85 = Evento.create(cliente_id: FLAVIOCRUZ.id, data_evento: '21-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
evento86 = Evento.create(cliente_id: BARBARASOUZA.id, data_evento: '27-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: MONTECASTELO.id)
evento87 = Evento.create(cliente_id: SALETEMICHELEEFLAVIO.id, data_evento: '28-07-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOTERRAZZA.id, observacao: 'ta com vera cerimonial e aldo silvestre')
evento88 = Evento.create(cliente_id: CAROLINACREPALDIETHALLES.id, data_evento: '11-08-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: VILAMANRESA.id, quantidade_horas: 6)
evento89 = Evento.create(cliente_id: RAPHAELALVEZ.id, data_evento: '11-08-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: ESPACOBELAVISTA.id)
evento90 = Evento.create(cliente_id: PAULA.id, data_evento: '17-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOMEDIEVALCASTELODOSVINHAIS.id)
evento91 = Evento.create(cliente_id: ARIANEEVALENTIN.id, data_evento: '18-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento92 = Evento.create(cliente_id: NATALIEBRUNO.id, data_evento: '18-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSANTAESPLENDORROOM.id)
evento93 = Evento.create(cliente_id: NEMELLYERAFAEL.id, data_evento: '15-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: HELENOFESTAS.id)
evento94 = Evento.create(cliente_id: JULIOOHIRA.id, data_evento: '27-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
evento95 = Evento.create(cliente_id: NICOLEKARINAAMAE.id, data_evento: '25-08-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:5, local_id: CASAPALMEIRA.id)
evento96 = Evento.create(cliente_id: TAYNA.id, data_evento: '06-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: RANCHOAVEIRO.id)
evento97 = Evento.create(cliente_id: LIDIANEBASCHIERA.id, data_evento: '06-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOSUPREMO.id)
evento98 = Evento.create(cliente_id: VANESSAFACCHIN.id, data_evento: '08-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOVILAVERDE.id)
evento99 = Evento.create(cliente_id: DEBORA.id, data_evento: '08-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:5, local_id: ESPACOSUPREMO.id)
evento100 = Evento.create(cliente_id: PAULORBERNARDES.id, data_evento: '15-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PEDREIRAQUINTADOLAGO.id)
evento101 = Evento.create(cliente_id: JESSICA2.id, data_evento: '15-09-2018 12:20:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: GUANABARA.id)
evento102 = Evento.create(cliente_id: MARINAEANDRE.id, data_evento: '15-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: MONTECASTELO.id)
evento103 = Evento.create(cliente_id: JULIANACESARGRANJA.id, data_evento: '22-09-2018 20:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: LANUIT.id, quantidade_horas: 7)
evento104 = Evento.create(cliente_id: VINICIUSDAFINE.id, data_evento: '22-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VIAAPPIA.id)
evento105 = Evento.create(cliente_id: NATHALIASUNIGAEFERNANDO.id, data_evento: '12-10-2018 21:00', tipo_evento_id:CASAMENTO.id, evento_status:4, local_id: LANUIT.id, quantidade_horas: 6)
evento106 = Evento.create(cliente_id: MAYRABONIN.id, data_evento: '12-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: THEROYALIMPERIAL.id)
evento107 = Evento.create(cliente_id: ALDOSILVESTRE.id, data_evento: '12-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VIAAPPIA.id)
evento108 = Evento.create(cliente_id: ALESSANDRAEMARCIO.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: GUANABARA.id)
evento109 = Evento.create(cliente_id: FLAVIACANTUSIORAFAELAELUCAS.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FAZENDALAGEADO.id)
evento110 = Evento.create(cliente_id: TALITAECLEVERTON.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2, local_id: VIAAPPIA.id)
evento111 = Evento.create(cliente_id: MARGARETHBARROS.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: PORTALGIRASSOL.id, observacao: 'Noivos: AMANDA E PAULO')
evento112 = Evento.create(cliente_id: BRUNAOLIVEIRA.id, data_evento: '13-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILLAFLOR.id)
evento113 = Evento.create(cliente_id: ERICDEMOURABRAMBILA.id, data_evento: '19-10-2018 00:00', tipo_evento_id:ANIVERSARIO.id, evento_status:1, local_id: CAMPINAS.id)
evento114 = Evento.create(cliente_id: PALOMAERODRIGOCARLAROSSINI.id, data_evento: '20-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: VIAAPPIA.id)
evento115 = Evento.create(cliente_id: RENATASARITAEEDUARDO.id, data_evento: '20-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: DUASMARIAS.id)
evento116 = Evento.create(cliente_id: ISABELACAUMEPAULO.id, data_evento: '20-10-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMMEDIEVAL.id)
evento117 = Evento.create(cliente_id: ANAFLAVIAEJEFERSON.id, data_evento: '03-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FLORIADAEVENTOS.id)
evento118 = Evento.create(cliente_id: PATRICIATENORIO.id, data_evento: '09-11-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:3, local_id: BOATEHIPICA.id)
evento119 = Evento.create(cliente_id: ANE.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: KRATOS.id)
evento120 = Evento.create(cliente_id: RICARDODOPRADOLAIA.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
evento121 = Evento.create(cliente_id: PAULOHENRIQUEDASILVA.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento122 = Evento.create(cliente_id: FELIPEMOREIRA.id, data_evento: '11-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMMEDIEVAL.id)
evento123 = Evento.create(cliente_id: NATALIA.id, data_evento: '15-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
evento124 = Evento.create(cliente_id: LARISSAHADASSAELUCIANO.id, data_evento: '15-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2, local_id: ALTODASPALMEIRAS.id)
evento125 = Evento.create(cliente_id: FABRINARIBEIRO.id, data_evento: '15-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACO55.id)
evento126 = Evento.create(cliente_id: PRISCILA.id, data_evento: '16-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: KRATOS.id)
evento127 = Evento.create(cliente_id: BrunaSumiregi.id, data_evento: '18-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: VILLAHARMONIA.id)
evento128 = Evento.create(cliente_id: KARINENICOLETI.id, data_evento: '24-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: MONTECASTELO.id)
evento129 = Evento.create(cliente_id: RAQUELEGUILHERME.id, data_evento: '24-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento130 = Evento.create(cliente_id: ANAPAULACASALMARINAEPEDRO.id, data_evento: '24-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ALTODASPALMEIRAS.id)
evento131 = Evento.create(cliente_id: ANDRESSA.id, data_evento: '24-11-2018 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CHACARARECANTODOSPASSAROS.id)
evento132 = Evento.create(cliente_id: DAIANEARAUJO.id, data_evento: '01-12-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: FONTESAOPAULO.id)
evento133 = Evento.create(cliente_id: BARBARAELUCAS.id, data_evento: '01-12-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2, local_id: HARASDAFAMILIA.id)
evento134 = Evento.create(cliente_id: GLAUCIAERENAN.id, data_evento: '19-01-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LEPARTIE.id)
evento135 = Evento.create(cliente_id: MARCELA.id, data_evento: '26-01-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: THEROYAL.id)
evento136 = Evento.create(cliente_id: ANACAROLINAELUIZ.id, data_evento: '02-03-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: GUANABARA.id)
evento137 = Evento.create(cliente_id: CYBELLE.id, data_evento: '03-03-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ESPACOMEDIEVALCASTELODOSVINHAIS.id)
evento138 = Evento.create(cliente_id: DANIELLIRAMOSTONHAI.id, data_evento: '13-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMCAMPESTRE.id)
evento139 = Evento.create(cliente_id: BRUNAEPEDRO.id, data_evento: '13-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: HIPICASOCIAL.id)
evento140 = Evento.create(cliente_id: JAQUELINE.id, data_evento: '23-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: BUFFETCLIMATROPICAL.id)
evento141 = Evento.create(cliente_id: CAROLINEEJOAO.id, data_evento: '27-04-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VILASAOVITO.id)
evento142 = Evento.create(cliente_id: TATIANA.id, data_evento: '09-06-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LANUIT.id)
evento143 = Evento.create(cliente_id: VIVIANE.id, data_evento: '22-06-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:3, local_id: AGUASDELINDOIA.id)
evento144 = Evento.create(cliente_id: FLAVIAERICAEMAURICIO.id, data_evento: '13-07-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento145 = Evento.create(cliente_id: ELLEN.id, data_evento: '23-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BUFFETIMAGEMMEDIEVAL.id)
evento146 = Evento.create(cliente_id: CAMILA.id, data_evento: '14-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: LAGOASANTARITA.id)
evento147 = Evento.create(cliente_id: KELMA.id, data_evento: '16-09-2019 00:00', tipo_evento_id:FORMATURA.id, evento_status:1, local_id: CAMPINAS.id)
evento148 = Evento.create(cliente_id: ELIZABETHNEGRAES.id, data_evento: '23-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMPINAS.id)
evento149 = Evento.create(cliente_id: THAISCAROLINEERENAN.id, data_evento: '28-09-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: BOSCH.id)
evento150 = Evento.create(cliente_id: JAQUELINERAPHAELZOTARELI.id, data_evento: '05-10-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: VERDANOEVENTOS.id)
evento151 = Evento.create(cliente_id: VANESSARODRIGUES.id, data_evento: '21-06-2019 00:00', tipo_evento_id:DEBUTANTE.id, evento_status:1, local_id: CAMPINAS.id)
evento152 = Evento.create(cliente_id: KARENEDANILO.id, data_evento: '23-08-2019 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: ANGELINOS.id)
evento153 = Evento.create(cliente_id: LIVIADESOUZARODRIGUES.id, data_evento: ' 13-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento154 = Evento.create(cliente_id: ARTHUR.id, tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: RANCHOAVEIRO.id)
evento155 = Evento.create(cliente_id: MAISAMOREIRA.id, data_evento: '03-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:1, local_id: CAMBARAFESTAS.id)
evento156 = Evento.create(cliente_id: THAYNARA.id, data_evento: '04-08-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
evento157 = Evento.create(cliente_id: ELAINE.id, data_evento: '01-04-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
evento158 = Evento.create(cliente_id: MARGARETHBARROS.id, tipo_evento_id:FORMATURA.id, evento_status:1, local_id: HOTELVITORIA.id)
evento159 = Evento.create(cliente_id: BIANCACLARA.id, data_evento: '22-09-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
evento160 = Evento.create(cliente_id: NATALIAPOLONICORREA.id, data_evento: '28-07-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento161 = Evento.create(cliente_id: MILENACAMPOS.id, data_evento: '22-12-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento162 = Evento.create(cliente_id: CAMILAPICCELICHOQUETA.id, data_evento: '28-10-2027 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento163 = Evento.create(cliente_id: LIVIACASTRO.id, data_evento: '14-07-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento164 = Evento.create(cliente_id: JESSICAGEREMIAS.id, data_evento: '20-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2, observacao: 'INDICAÇAO DE UM PROFISSIONAL - PELA MAE CLAUIDIA ASSIONE')
evento165 = Evento.create(cliente_id: MARGARETHBARROS.id, tipo_evento_id:FORMATURA.id, evento_status:1, local_id: WETNWILD.id)
evento166 = Evento.create(cliente_id: NAYARAMACANOSSO.id, data_evento: '18-08-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento167 = Evento.create(cliente_id: TANIAMARIAFORTUNATO.id, data_evento: '13-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento168 = Evento.create(cliente_id: VERONICA.id, data_evento: '10-11-2018 00:00', tipo_evento_id:CASAMENTO.id, evento_status:2)
evento169 = Evento.create(cliente_id: CAMILAEFABIO.id, data_evento: '20-05-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2, observacao: 'CLIENTE NÃO ESTA NO MAILING')
evento170 = Evento.create(cliente_id: THAISEPEDRO.id, data_evento: '20-10-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento171 = Evento.create(cliente_id: THAINAEHENRIQUE.id, data_evento: '19-05-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento172 = Evento.create(cliente_id: LARISSAEVINICIUS.id, data_evento: '24-11-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento173 = Evento.create(cliente_id: REBECAEFELIPE.id, data_evento: '08-09-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)
evento174 = Evento.create(cliente_id: ROBERTAEKAIO.id, data_evento: '18-08-2018 00:00', tipo_evento_id:OUTROS.id, evento_status:2)


###########################################################################################################################
######################################################## PROPOSTAS ########################################################
###########################################################################################################################
evento1.proposta.create( descricao: "8683 - 20 LED UV + 20M DE TRELIÇA + MESA DMX", ativa: true)
evento2.proposta.create( descricao: "0-ANIMAÇÃO LASER -  1 LASER RBG DA DJ E 1 LASER RGB EVANDRO - 1 LASER VERDE EVANDRO.      EM ABERTO DJ PARA O EVENTO NO VALOR DE R4 1200,00", ativa: true)
evento3.proposta.create( descricao: "0-OPCAO 02+LED WASH+ PISTA COM 2 CIRCULARES + 20 GLOBOS, 1 LASER COLORIDO+ 1 TELAO WIDE (OU VIDEOWALLL),  34 PAR 38 + 8 PAR LED BANDA E DJ NA LATERAL", ativa: true)
evento4.proposta.create( descricao: "8220-OPÇÃO 01 SUSPENSO (USAR UMA CAIXA DE SOM DENTRO DO SALAO)  + 48PBIM + 16P38 + CORTINA DE LED  3X3 + SOM CERIMONIA + VIDEO WALL 4 TELAS + 2 TV NO SALAO (so vai tocar 3 jmusica na cerimonia) ", ativa: true)
evento5.proposta.create( descricao: "8538-TRAVE 4X6 COM DUAS COLUNAS POR LADO + 1 QSC + 4 MHEAD + 2 REF LED + FUMAÇA + 3 TV 46 NO PEDESTAL", ativa: true)
evento6.proposta.create( descricao: "0-0", ativa: true)
evento7.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem? A Dina do Lellit pediu que eu fizesse contato contigo, ela disse que eu ligaria para falarmos da musicalidade da sua festa por acaso??", ativa: true)
evento8.proposta.create( descricao: "8561-opção 01 + 300 + viudeo wall 9 telas ou 4 tv separada", ativa: true)
evento9.proposta.create( descricao: "8642-ORÇ 2016", ativa: true)
evento10.proposta.create( descricao: "0-ORÇ 2016 + 400", ativa: true)
evento11.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento12.proposta.create( descricao: "8648-ORÇ 2016 + DJ ANDRE CURADO", ativa: true)
evento13.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento14.proposta.create( descricao: "8108-ORÇ 2016", ativa: true)
evento15.proposta.create( descricao: "8644-OPÇÃO 01 + 40PBIM + 16 PAREDE + VIDEO WALL 9 TELAS", ativa: true)
evento16.proposta.create( descricao: "8062-ORÇ 2016", ativa: true)
evento17.proposta.create( descricao: "8650-MONTAGEM EM TORRES ", ativa: true)
evento18.proposta.create( descricao: "8152-ORÇ 2016 + 400", ativa: true)
evento19.proposta.create( descricao: "8688-TRAVE + 2 TVS", ativa: true)
evento20.proposta.create( descricao: "8672-ORÇ 2016 + 400 + telao suspenso", ativa: true)
evento21.proposta.create( descricao: "8687-TRAVE 4X4 + VIDEO WALL 9 TELAS + VEEJAY + 16P38", ativa: true)
evento22.proposta.create( descricao: "0-DJ + 2 TVS", ativa: true)
evento23.proposta.create( descricao: "8303 -2       8303 -3-OPCAO  COM 12 MOVING + 16 PAR 38 + 24 PIM BIM", ativa: true)
evento24.proposta.create( descricao: "0-ORÇ 2016 + VIDEO WALL 4 TELAS + PISO DE LED", ativa: true)
evento25.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento26.proposta.create( descricao: "8361-MOTAGEM EM TORRES", ativa: true)
evento27.proposta.create( descricao: "7639-ORÇ 2016", ativa: true)
evento28.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento29.proposta.create( descricao: "8084-OPÇÃO 01 C 8MOVING HEAD + VIDEO WALL 9 TELAS", ativa: true)
evento30.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento31.proposta.create( descricao: "0-DJ E EQUIPAMENTO", ativa: true)
evento32.proposta.create( descricao: "8667-OPÇÃO 01 + 14 GLOBOS 50CM + CABINE MAPEADA COM PALCO + 24 P38", ativa: true)
evento33.proposta.create( descricao: "8316-OPÇÃO 01 MONTADO EM TRAVE ( SEM GLOBOS ESPELHO) + 32PBIM + 20P38 + SOM DA CERIMONIA", ativa: true)
evento34.proposta.create( descricao: "8587-OPÇÃO 01 + ENCAPE PERNAS (verificar o que adequa melhor se se permitem preder no madeiramento) (sendo duas caixas de som em outro ambiente) + 2 video wall 4 telas + ", ativa: true)
evento35.proposta.create( descricao: "8669-DUAS CAIXAS DE SOM E DJ COM EQUIPAMENTO - cerimonia e jantar", ativa: true)
evento36.proposta.create( descricao: "8230-SISTEMA DE SOM COM 4 CX EM PEDESTAL E DJ COM EQUIPAMENTO", ativa: true)
evento37.proposta.create( descricao: "8141-OPÇÃO 01 + 300 + 48PBIM + 32P38 + 8HQI (4 VERDE E 4 BRANCA CERIMONIA + 1 VARAL DE LAMPADAS + SOM CERIMONIA)", ativa: true)
evento38.proposta.create( descricao: "8323-OPCAO 01 ENCAPE DA ESTRUTURA + LASER VERDE 1W + TURBO AIR", ativa: true)
evento39.proposta.create( descricao: "8586-OPÇÃO 01 + ENCAPE ESTRUTURA + VIDEO WALL 4 TELAS", ativa: true)
evento40.proposta.create( descricao: "8657-TRAVE COM VIDEO WALL", ativa: true)
evento41.proposta.create( descricao: "8309-MONTAGEM EM TRAVE COM 2TV CORTESIA", ativa: true)
evento42.proposta.create( descricao: "7266-ORÇ 2014", ativa: true)
evento43.proposta.create( descricao: "8122-0", ativa: true)
evento44.proposta.create( descricao: "8301-ORÇ 2016 + 300", ativa: true)
evento45.proposta.create( descricao: "8276-OPÇAO 01 + ENCAPE E FECHAMENTO ATRAS DO DJ PRETO + TELAO WIDE + 40 PBIM + 16P38", ativa: true)
evento46.proposta.create( descricao: "8653-OPÇÃO 01 + TELAO WIDE", ativa: true)
evento47.proposta.create( descricao: "8625-OPÇÃO 01 + VIDEO WALL 4 TELAS", ativa: true)
evento48.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento49.proposta.create( descricao: "8613-OPÇÃO 01", ativa: true)
evento50.proposta.create( descricao: "0-0", ativa: true)
evento51.proposta.create( descricao: "8621-QUINTA DAS BROMELIAS", ativa: true)
evento52.proposta.create( descricao: "0-TRAVE COM VIDEO WALL", ativa: true)
evento53.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento54.proposta.create( descricao: "8310-OPÇÃO 1 + VIDEOWALL", ativa: true)
evento55.proposta.create( descricao: "8605-OPÇÃO 01 COM 8MHEAD + VIDEO WALL 9 TELAS", ativa: true)
evento56.proposta.create( descricao: "8676-TRAVE COM 4 MOVING HEAD", ativa: true)
evento57.proposta.create( descricao: "8662-100 Iluminação Arquitetural de mesa - Penbeam<br />20 Iluminação Arquitetural para paredes (8 par 38 - 12 set light)<br />36 Iluminação de Led RGB  com troca de cores via mesa DMX<br />10 Iluminação de vapor de gás (Externa e fachadas)<br />1 Varal de lampadas - 100mt<br />1 Rack AC.<br />1  palco 08x06x0,50", ativa: true)
evento58.proposta.create( descricao: "0-PISO LED ", ativa: true)
evento59.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento60.proposta.create( descricao: "8551-SISTEMA DE SOM E DJ", ativa: true)
evento61.proposta.create( descricao: "8601-0", ativa: true)
evento62.proposta.create( descricao: "8246-TRAVE COM + 24PBIM", ativa: true)
evento63.proposta.create( descricao: "8582-OPCAO 01 + 300 + 32P38 + 40 PBIM", ativa: true)
evento64.proposta.create( descricao: "8591-TRAVE COM VIDEO WALL + 200M DE VARAL DE LUZES", ativa: true)
evento65.proposta.create( descricao: "8270-PACOTE 1 COM 8 BEAN + DJ ANDRÉ CURADO+ VIDEOWALL 4 TVS + 40 PIMBIM+32 P38 ", ativa: true)
evento66.proposta.create( descricao: "8578-PISTA OPCAO 02 + PES ENCAPADO + TELAO WIDE + DEEJAZZ + LAZER VERDE + 40 PIM BIM  + 32 PAR 38 + 12 HQI", ativa: true)
evento67.proposta.create( descricao: "8317-SISTEMA DE SOM E DJ COM 10 LED", ativa: true)
evento68.proposta.create( descricao: "0-DJ E EQUIPAMENTO", ativa: true)
evento69.proposta.create( descricao: "8593-DJ E EQUIPAMENTO", ativa: true)
evento70.proposta.create( descricao: "8679-sistema de som ambiente ou erstrutura trave com video wall", ativa: true)
evento71.proposta.create( descricao: "8679-2-VER DUAS PROPOSTAS", ativa: true)
evento72.proposta.create( descricao: "8321-TRAVE COM VIDEO WALL + ALGUNS EQUIPAMNTOS (banda R$ 1900,00)", ativa: true)
evento73.proposta.create( descricao: "0-TRAVE COM VIDEO WALL", ativa: true)
evento74.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento75.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento76.proposta.create( descricao: "8645-DJ E EQUIPAMENTO", ativa: true)
evento77.proposta.create( descricao: "0-ORÇ 2016 + VIDEO WALL 4 TELAS CORTESIA", ativa: true)
evento78.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento79.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento80.proposta.create( descricao: "8686-trave com encape e fechamento atras do dj com video wall 8 telas + 24p38 + 40pbim", ativa: true)
evento81.proposta.create( descricao: "8680-ORÇ 2016 + TELAO SUSPENSO + 40PBIM + 16P38", ativa: true)
evento82.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento83.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento84.proposta.create( descricao: "0-0", ativa: true)
evento85.proposta.create( descricao: "0-ORÇ TRAVE COM VIDEO WALL", ativa: true)
evento86.proposta.create( descricao: "0-ORÇ 2016 + 400", ativa: true)
evento87.proposta.create( descricao: "0-ORÇ 2016 (TELAO, 16 P38 + 16PBIM CORTESIA)", ativa: true)
evento88.proposta.create( descricao: "8597-OPÇÃO 02 + DJ ALEXANDRE + ENCAPE PRETO DA ESTRUTURA + LASER SHOW VERDE + CABINE MAPEADA + PALCO 6X2 + 40PBIM + 24P38 + 6HQI + TURBO AIR + LIVE PERCUSSION", ativa: true)
evento89.proposta.create( descricao: "8647-OPÇAO 01 + 35LED + 50PBIM + 2SKYLITE +  PAINEL LED 12M + PISO LED SENSITIVO", ativa: true)
evento90.proposta.create( descricao: "8603-OPÇÃO 01 COM 8 MOVINH HEAD", ativa: true)
evento91.proposta.create( descricao: "0-ORÇ 2016 + (1 telao + encape e fechamento atras do dj cortesia)", ativa: true)
evento92.proposta.create( descricao: "8288-0", ativa: true)
evento93.proposta.create( descricao: "8622-SISTEMA DE SOM E DJ COM ILUMINAÇÃO ARQUITETURAL", ativa: true)
evento94.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento95.proposta.create( descricao: "8654-0", ativa: true)
evento96.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento97.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento98.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento99.proposta.create( descricao: "0-ORÇ 2016 (cortesia encape e fechamento)", ativa: true)
evento100.proposta.create( descricao: "8543-ORÇ 2016 + 300", ativa: true)
evento101.proposta.create( descricao: "8606-SISTEMA DE SOM E DJ COM 24P38", ativa: true)
evento102.proposta.create( descricao: "0-ORÇ 2016 + 400", ativa: true)
evento103.proposta.create( descricao: "8610-OPÇÃO 1 - PISO DE LED - 1 VIDEOWALL 4 TELAS -  DEEJAZZ", ativa: true)
evento104.proposta.create( descricao: "8635-48 pbim + 54p38 + rackdimer", ativa: true)
evento105.proposta.create( descricao: "8235-ORÇ 2016 - 1 VIDEO WALL 9 TELAS + DEEJAZ", ativa: true)
evento106.proposta.create( descricao: "8626-OPÇÃO 01 MONTADO EM TRAVE + ENCAPE PERNAS E TECIDO ATRAS DO DJ", ativa: true)
evento107.proposta.create( descricao: "8646-0", ativa: true)
evento108.proposta.create( descricao: "8658-ORÇ 2016 + FECHAMENTO E ENCAPE PRETO  + 56PBIM + 16 P38 + TELAO WIDE", ativa: true)
evento109.proposta.create( descricao: "8335-ORÇ 2016 + 400 + SOM CERIMONIA", ativa: true)
evento110.proposta.create( descricao: "8638-1-Peam Beam<br />2-Iluminacao do ambiente - decoração Aldo<br />3-Dois Projetores para passar os vídeos e fotos", ativa: true)
evento111.proposta.create( descricao: "8326-ORÇ 2016", ativa: true)
evento112.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento113.proposta.create( descricao: "0-ORÇ TRAVE COM VIDEO WALL", ativa: true)
evento114.proposta.create( descricao: "0-70 PIM BIM + 24 PAR 38 + 10 PAR 38 HALL + 2 TELOES", ativa: true)
evento115.proposta.create( descricao: "8649-0", ativa: true)
evento116.proposta.create( descricao: "0-ORÇ 2016 COM 8 MHEAD", ativa: true)
evento117.proposta.create( descricao: "8615-TRAVE COM VIDEO WALL", ativa: true)
evento118.proposta.create( descricao: "0-ORC 2018", ativa: true)
evento119.proposta.create( descricao: "8610-OPÇAO 01 SUSPENSO + 2 TELOES SUSPENSOS + 2 TV NA CABINE DO DJ + PALCO PARA O DJ (VAI TER BANDA)", ativa: true)
evento120.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento121.proposta.create( descricao: "0-ORÇ 2016 + TELAO SUSPENSO", ativa: true)
evento122.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento123.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento124.proposta.create( descricao: "0-DJ E EQUIPAMENTO", ativa: true)
evento125.proposta.create( descricao: "0-OPÇÃO 01 + 300 FRETE", ativa: true)
evento126.proposta.create( descricao: "0-ORC 2018", ativa: true)
evento127.proposta.create( descricao: "0-ORC 2018", ativa: true)
evento128.proposta.create( descricao: "8661-OPÇÃO 01 COM 8MHEAD + 400 FRETE + VIDEO WALL 8 TELAS + 18LED SALAO DE CIMA", ativa: true)
evento129.proposta.create( descricao: "8556-ORÇ 2016 + VIDEO WALL 9 TELAS + FECHAMENTO EM TECIDO PRETO", ativa: true)
evento130.proposta.create( descricao: "0-DJ E EQUIPAMENTO", ativa: true)
evento131.proposta.create( descricao: "8641-OPÇÃO 01 + ENCAPE  E FECHAMENTO PRETO + PISO DE LED + TELASO SUSPENSO + 20LED DMX", ativa: true)
evento132.proposta.create( descricao: "8660-TEM PAINEL DE LED", ativa: true)
evento133.proposta.create( descricao: "0-ILUMINAÇÃO RUSTICA, VARAL LAMPADAS, QHI AMBAR", ativa: true)
evento134.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento135.proposta.create( descricao: "0-ORC 2018", ativa: true)
evento136.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento137.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento138.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento139.proposta.create( descricao: "8684-OPÇÃO 01 COM 8 MOVING", ativa: true)
evento140.proposta.create( descricao: "0-ORC 2018", ativa: true)
evento141.proposta.create( descricao: "8651-OPÇÃO 01 COM 10 GLOBOS + PAINEL DE LED 12M.", ativa: true)
evento142.proposta.create( descricao: "8652-ORÇ 2016 + VIDEO WALL", ativa: true)
evento143.proposta.create( descricao: "0-ORC 2018", ativa: true)
evento144.proposta.create( descricao: "8682-opção 01 + video wall 4 telas", ativa: true)
evento145.proposta.create( descricao: "8568-ORÇ 2016 + PAINEL DE LED", ativa: true)
evento146.proposta.create( descricao: "8664-OPÇÃO 01 + 56pbim + 16p38 + VIDEO WALL 4 TELAS + Ppiso 5x5", ativa: true)
evento147.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento148.proposta.create( descricao: "7912-ORÇ 2016", ativa: true)
evento149.proposta.create( descricao: "8614-ORÇ 2016", ativa: true)
evento150.proposta.create( descricao: "0-TRAVE COM VIDEO WALL", ativa: true)
evento151.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento152.proposta.create( descricao: "0-ORÇ 2016", ativa: true)
evento153.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento154.proposta.create( descricao: "8616-0", ativa: true)
evento155.proposta.create( descricao: "0-ORÇ TRAVE COM VIDEO WALL", ativa: true)
evento156.proposta.create( descricao: "0-Oi Thaynara, aqui é o Fabio da Dj Sonorização, tudo bem?<br />te liguei na sexta, se lembra?<br />Se quiser conversar por aqui, fico online tempo todo.<br />Eu fiz uma colagem com algumas imagens de alguns serviços que fazemos e achei legal compartinhar com vc. as vezes tem algo que vc goste por ali.<br />Se tiver em tempo de ver essa parte, vamos agendar uma renuiao com vc e o Jader.", ativa: true)
evento157.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, ela disse que eu ligaria para falarmos da musicalidade da sua festa por acaso??", ativa: true)
evento158.proposta.create( descricao: "8073-OPÇÃO 01 + ENCAPAMENTO DAS PERNAS E CABINE DO DJ + LASER VERDE + 04 BEAN + 1 TELAO WIDE + 6 TV42 + VJ + 56PBIM + 24P38 + 7 REFLETOR PARA MESA DIRETIVA + TURBO AIR", ativa: true)
evento159.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento160.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento161.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento162.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento163.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento164.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento165.proposta.create( descricao: "8074-VARIOS EQUIPAMENTOS - POSSUI UMA VARIAÇÃO COM SOM PARA COLAÇÃO E OUTRA SEM", ativa: true)
evento166.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento167.proposta.create( descricao: "0-aqui é o Fabio da Dj Sonorização, tudo bem?<br />A Dina do Lellit pediu que eu fizesse contato contigo, por acaso ela disse que eu ligaria pra falar do Dj da sua festa??", ativa: true)
evento168.proposta.create( descricao: "0-Olá Veronica, como vai?<br />Recebemos a recomendação para nos apresentarmos a você, sei que vai se casar em novembro do ano que vem!<br />Se haver interesse em pesquisar por dj, som e iluminação decorativa entre em contato!<br />Fabio, <br />www.djsonorização.com.br<br />(este numero tb é whats)", ativa: true)
evento169.proposta.create( descricao: "0-Sei que vão se casar em breve e através da Renata Melo da 2M eventos cheguei até vocês e como lembrete assim que for tempo vejam nossa empresa; @djsonorizacao, estamos online na maioria das redes sociais e pelos contatos abaixo!<br />Anexo vai uma colagem de algumas coisas que podemos fazer! Claro que há mais itens, e dessa forma fica nosso convite aberto a nos reunirmos.<br />Att", ativa: true)
evento170.proposta.create( descricao: "0-Sei que vão se casar em breve e através da Renata Melo da 2M eventos cheguei até vocês e como lembrete assim que for tempo vejam nossa empresa; @djsonorizacao, estamos online na maioria das redes sociais e pelos contatos abaixo!<br />Anexo vai uma colagem de algumas coisas que podemos fazer! Claro que há mais itens, e dessa forma fica nosso convite aberto a nos reunirmos.<br />Att", ativa: true)
evento171.proposta.create( descricao: "0-Sei que vão se casar em breve e através da Renata Melo da 2M eventos cheguei até vocês e como lembrete assim que for tempo vejam nossa empresa; @djsonorizacao, estamos online na maioria das redes sociais e pelos contatos abaixo!<br />Anexo vai uma colagem de algumas coisas que podemos fazer! Claro que há mais itens, e dessa forma fica nosso convite aberto a nos reunirmos.<br />Att", ativa: true)
evento172.proposta.create( descricao: "0-Sei que vão se casar em breve e através da Renata Melo da 2M eventos cheguei até vocês e como lembrete assim que for tempo vejam nossa empresa; @djsonorizacao, estamos online na maioria das redes sociais e pelos contatos abaixo!<br />Anexo vai uma colagem de algumas coisas que podemos fazer! Claro que há mais itens, e dessa forma fica nosso convite aberto a nos reunirmos.<br />Att", ativa: true)
evento173.proposta.create( descricao: "0-Sei que vão se casar em breve e através da Renata Melo da 2M eventos cheguei até vocês e como lembrete assim que for tempo vejam nossa empresa; @djsonorizacao, estamos online na maioria das redes sociais e pelos contatos abaixo!<br />Anexo vai uma colagem de algumas coisas que podemos fazer! Claro que há mais itens, e dessa forma fica nosso convite aberto a nos reunirmos.<br />Att", ativa: true)
evento174.proposta.create( descricao: "0-Sei que vão se casar em breve e através da Renata Melo da 2M eventos cheguei até vocês e como lembrete assim que for tempo vejam nossa empresa; @djsonorizacao, estamos online na maioria das redes sociais e pelos contatos abaixo!<br />Anexo vai uma colagem de algumas coisas que podemos fazer! Claro que há mais itens, e dessa forma fica nosso convite aberto a nos reunirmos.<br />Att", ativa: true)
