# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Local.create(nome: 'PLAZA HOTEL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'REGISTRO - Rua Dr Benedito Martins Barbosa 78 – Vila Tupi', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: '3M CLUBE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ADLER MIX', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ALPHAVILLE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'Altino Gouveia n 976 - Valinhos SP.  - Jd Pinheiros ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ALTO DAS PALMEIRAS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'AMCHAM BUSINESS CENTER  AV DR JOSE BONIFACIO COUTINHO NOGUEIRA  N150 ED GALLERIA PLAZA CAMPINAS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'AMPARO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ANGELINOS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ANGELINOS - COLEGIO PIO XII', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ARTUR NOGUEIRA - AIDAN', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ATIBAIA HARAS - Hotel Haras de Atibaia', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'Av. Cel. Silva Teles, 843 - Cambuí, Campinas - SP, 13024-001 (19) 3294-8133', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BARACAT', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BOATE OURO NEGRO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BOB', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BONVENON EVENTOS - Av Lix da Cunha 103 - Vila Industrial', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BOSCH', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BROOKLIN SP', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BUFFET IMAGEM CAMPESTRE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BUFFET IMAGEM CONTEMPORANEO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BUFFET SERRA DOS CRISTAIS - Rodovia Tancredo Neves (Estrada Velha para São Paulo), 861 Km 54 - Bairro Castanho - Jundiaí/SP', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BUFFET SUMATRA - LOUVEIRA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'BUTANTÃ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CAMPINAS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CAMPINAS - Av. Do ipiranga, 447', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CAMPINAS - LOJA DECATLHON', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CAMPINAS PRAÇA CAPITA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CANTO DA FLORESTA - AMPARO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CASA TERRANA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CASARAO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CASARÃO ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CHACARA DO LAGO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'Clube CERAMICA MOGI GUAÇU', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CLUBE DE CAMPO POUSO ALEGRE MG', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CLUBE MOGIANO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CLUBE VETERANOS JUNDIAI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CONDOMINIO  PEDRA ALTA - ROD MAKENZIE KM5', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'CONDOMINIO MARAMBAIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'DEBUTANTES HIPICA 2016', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'DUAS MARIAS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ENFLOR - ANDRE PEDROTI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPACO BARAO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO BARAO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO BARÃO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO BELA VISTA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO BELA VISTA ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO GUANABARA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO MONTE CASTELO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO SANTA FILOMENA ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO SANTA MARIA (PARQUE JAMBEIRO rua ana santina pereira N45)', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO SUPREMO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESPAÇO TERRAZZA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESTACAO BARONEZA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESTAÇÃO BARONEZA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ESTACAO CULTURA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'EXPO NOIVAS       VIA APPIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FANTAO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FAZENDA CAPITUVA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FAZENDA DAS CABRAS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FAZENDA LAGEADO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FAZENDA SANTA BARBARA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FAZENDA SANTA MARGARIDA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FAZENDA STA BARBARA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FAZENDA STA BARBARA - ITATIBA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FLORIADA EVENTOS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FONTE SANTA TEREZA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FONTE SAO PAULO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FONTE SAO PAULO - FICA MONTADO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'FONTE SAO PAULO - MONTA NO DIA 07-12', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'GOLDEN ROOM', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'GRAN FLORA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'GRAN FLORA – TS BRASIL ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'GRANFLORA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'GUANABARA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HIPICA - BOATE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HIPICA - PISCINA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HIPICA - SOCIAL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLAMBRA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLAMBRA - DE WIT', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLAMBRA - ENFLOR', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLAMBRA - GRANFLORA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLAMBRA - VELINING MARKET', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLAMBRA GRAN FLORA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLAMBRA RESIDENCIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLE 19', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLMBRA - GRANFLORA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOLMBRA - GRANFLORA - MONTA DIA 06-12', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HORTOLANDIA - AMISTED MAXION - Rua rua dez, sn bairro - jardim sao camilo', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'Hotel Meliá Campinas: R. Severo Penteado, 140 - Cambuí, Campinas - SP, 13025-050', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOTEL NACIONAL IN', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOTEL PREMIUM - • Rua Novotel, 931 - Jardim Nova Aparecida, Campinas - SP', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOTEL SOL DO MOGI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOTEL VITORIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOTEL VITORIA ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HOTEL VITORIA - MONTA DIA 08-12 AS 14:00', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'HYPNOSE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'INDAIATUBA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'INDAIATUBA CLUBE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ITATIBA - ESPAÇO DONA INES            montagem liberada um dia antes na sexta', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ITUPEVA - Av. Um,Jundiaí - SP,', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ITUPEVA - FAZENDA VILA AMOREIRAS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ITUPEVA Condomínio Fazenda da Grama Rodovia Miguel Melhado Campos, km 83,5 - Itupeva http://www.fazendadagrama.com.br/', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - 12 DE SETEMBRO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - CRUZEIRO DO SUL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - EUROPA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - FLORIPA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - MAIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - MICHEL MARTINI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - NASIF', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - RESIDENCIA FAMILIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - ROSEIRA DE BAIXO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - ROSEIRA DE CIMA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'JAGUARIUNA - SÃO JOSE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'KINOPLEX', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'KRATOS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'LA NUIT', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'LAGOA SANTA RITA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'LALOUETE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'LANUIT', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'LE BLANC', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'LE VELMONT', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'LELUH - Rua Pedro Donda, nº 47 - Jd. Esplanada II', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MALCAL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MANSAO THIAGO HADI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MIDIA FEST 2014 / TENIS CLUBE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MOINHO SANTA CANDIDA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MONET EVENTOS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MONREALE HOTEL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MONTE CASTELO - INFERIOR', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MONTE CASTELO - SUPERIOR', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MONTE MOR - ·      Local: Rod. Campinas/Capivari, Km 23,5, Bairro: Chapéu do Sol', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'MONTET EVENTOS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'NOVA ODESSA VILLA HARMONIA ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'PAULINENSE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'PAULINIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'PEDREIRA - BUFFET CANOA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'PHILADELFIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'PLAZA HOTEL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'PLAZA HOTEL LIBERADO AS 09:00', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'POÇOS DE CALDAS - CASA SALES - Av. João Pinheiro, 5700 - Bortolan - Poços de Caldas-MG  ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'PORTAL GIRASSOL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'POT POURRIT CLASSICO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'POTPORRIT CLASSICO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'QUINTA DAS BROMELIAS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'QUINTA DAS BROMELIAS ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RASEN', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RASEN - LIBERADO AS 13:00', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RESIDENCIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RESTAURANTE CACHOEIRA ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RETIRA CONOSCO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RETIRAR NO BARRACAO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RIBEIRAO PRETO - ESPAÇO GOLF - Rodovia Dr. Antônio Duarte Nogueira, Km 316 - Anel Viário Contorno Sul', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ROYAL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RUA BARRETO LEME 1637', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'Rua Frei Manoel da Ressurreição, 1181 - Jardim Guanabara, Campinas – SP', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'rua Paiquerê 165 casa 13, condomínio Monte Carlo, Bairro: Jardim Paquere, CEP 13271-600, Valinhos', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'RUDA (BARÃO GERALDO)', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SALAO CONDOMINIO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SÃO CARLOS - VOLENTRI - Passeio das Castanheiras, 480 – Pq Faber ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SÃO JOAO DA BOA VISTA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SÃO PAULO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SEDE ROCKIT - CAMPINAS ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SHOP D. PEDRO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SHOPING IGUATEMI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SOCORRO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SOLAR DE JUNDIAI - Rodovia Engenheiro Constâncio Cintra, S/n - Champirra, Jundiaí - SP', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SORIA EVENTOS  Endereço: Rua Aparecida, 1470 - Sorocaba /SP', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SP 107, Rua Eduardo Selingardi, s/n - Fazenda Filomena. Santo Antonio da Posse/SP', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'SPAZIO TRAMONTI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'STEIN KAIS -  Norte Sul 252', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'TEMAKERIA E CIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'TENIS CLUBE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'TENIS CLUBE – Liceu Médio', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'TENIS CLUBE AGUAS DE LINDOIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'TENIS CLUBE AGUAS DE LINDOIA  - RUA PREFEITO ADOLFO MANTOVANI (IR ATÉ O FINAL FICA EM CIMA DO MORRO)', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'TENIS CLUBE ITAPIRA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'THE ROYAL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'THE ROYAL - CASA DE CAMPO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'THE ROYAL - IMPERIAL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'THE ROYAL PASSO DOS NOBRES', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'UNISAL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VALINHOS SEDE EMPRESA - Endereço: Estrada Municipal Governador Mário Covas, 641 - Portal do Anhanguera - Rua B, 161 - Macuco, Valinhos - SP, 13279-441', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VEILING', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VEILING HOLAMBRA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VEILLING HOLAMBRA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VERT EVENTOS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VIA APPIA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VIA APPIA - FORMATURA AVE MARIA ENSINO MÉDIO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VIA APPIA - IMACULADA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VIA APPIA - LICEU', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VIA APPIA (COMUNITARIA)', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VICTORIA HALL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VICTORIA HOTEL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VICTORIAS EVENTOS', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILA BELA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILA DANGELO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILA ROSSA - SÃO ROQUE', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILLA DANGELO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILLA DANGELO - ITATIBA ', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILLA DELIKATESSEN', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILLA GRETTA - VINHEDO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VILLA RICCI', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VINHEDO', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VINHEDO - ACADEMIA MOVE FIT', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VINHEDO - Av. Invernada, 3237 – Pq Nova Suiça – Valinhos - Perto do Shop. Valinhos', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VINHEDO PLAZA HOTEL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VITORIA HALL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VITORIA HALL salão principal  - cerimônia  será  Sala Santorin', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'VITORIA HOTEL', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')
Local.create(nome: 'ZANZARA', endereco: 'Campinas', cidade: 'Campinas', estado: 'SP', telefone: '12345678', nome_contato: 'nome', email: 'email@email.com')